xcopy c:\sge\contab\GlobaisESTARTX.dll C:\Expedicao\Atualizacao\pgm_artlux\GlobaisESTARTX.dll /Y
xcopy c:\sge\contab\RotinasESTARTX.dll C:\Expedicao\Atualizacao\pgm_artlux\RotinasESTARTX.dll /Y
xcopy c:\sge\contab\TelasESTARTX.ocx C:\Expedicao\Atualizacao\pgm_artlux\TelasESTARTX.ocx /Y
xcopy c:\sge\contab\GlobaisAdmArtMill.dll C:\Expedicao\Atualizacao\pgm_artmill\GlobaisAdmArtMill.dll /Y
xcopy c:\sge\contab\GlobaisTelasESTArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\GlobaisTelasESTArtmill.dll /Y
xcopy c:\sge\contab\GlobaisTelasFATArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\GlobaisTelasFATArtmill.dll /Y
xcopy c:\sge\contab\RotinasAdmArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasAdmArtmill.dll /Y
xcopy c:\sge\contab\RotinasCRFATArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasCRFATArtmill.dll /Y
xcopy c:\sge\contab\RotinasESTArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasESTArtmill.dll /Y
xcopy c:\sge\contab\RotinasFATArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasFATArtmill.dll /Y
xcopy c:\sge\contab\RotinasMATArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasMATArtmill.dll /Y
xcopy c:\sge\contab\RotinasPVArtmill.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasPVArtmill.dll /Y
xcopy c:\sge\contab\RotinasTRBX.dll C:\Expedicao\Atualizacao\pgm_artmill\RotinasTRBX.dll /Y
xcopy c:\sge\contab\TelasESTArtmill.ocx C:\Expedicao\Atualizacao\pgm_artmill\TelasESTArtmill.ocx /Y
xcopy c:\sge\contab\TelasFATArtmill.ocx C:\Expedicao\Atualizacao\pgm_artmill\TelasFATArtmill.ocx /Y
xcopy c:\sge\contab\RotinasFATINO.dll C:\Expedicao\Atualizacao\pgm_inopat\RotinasFATINO.dll /Y
xcopy c:\sge\contab\GlobaisPVPar.dll C:\Expedicao\Atualizacao\pgm_parolibor\GlobaisPVPar.dll /Y
xcopy c:\sge\contab\GlobaisTelasFATPar.dll C:\Expedicao\Atualizacao\pgm_parolibor\GlobaisTelasFATPar.dll /Y
xcopy c:\sge\contab\RotinasESTPar.dll C:\Expedicao\Atualizacao\pgm_parolibor\RotinasESTPar.dll /Y
xcopy c:\sge\contab\TelasFATPar.ocx C:\Expedicao\Atualizacao\pgm_parolibor\TelasFATPar.ocx /Y
xcopy c:\sge\contab\GlobaisTelasCPRX.dll C:\Expedicao\Atualizacao\pgm_versaox\GlobaisTelasCPRX.dll /Y
xcopy c:\sge\contab\RotinasAdmX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasAdmX.dll /Y
xcopy c:\sge\contab\RotinasCPRX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasCPRX.dll /Y
xcopy c:\sge\contab\RotinasESTX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasESTX.dll /Y
xcopy c:\sge\contab\RotinasFATX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasFATX.dll /Y
xcopy c:\sge\contab\RotinasLojaX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasLojaX.dll /Y
xcopy c:\sge\contab\RotinasTRBX.dll C:\Expedicao\Atualizacao\pgm_versaox\RotinasTRBX.dll /Y
xcopy c:\sge\contab\TelasCPRX.ocx C:\Expedicao\Atualizacao\pgm_versaox\TelasCPRX.ocx /Y
xcopy c:\sge\contab\TelasFATX.ocx C:\Expedicao\Atualizacao\pgm_versaox\TelasFATX.ocx /Y
xcopy c:\sge\contab\admlib2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\ADRelVB2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchCOM.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchCPR2.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchEST2.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchFATInt.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchFIS.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchTransfCC.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\BatchTransfECF.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\contabbatch2.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\ContabOnLine2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\DicGlobais2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\DicPrincipal2.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\DicRotinas2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisAdm2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisCOM.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisContab2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisCPR2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisCRFAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisEST2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisFAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisFIS.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisLoja.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisMAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisPCP2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisPRJ.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisPV2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisSRV2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasCOM.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasCPR2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasCTB2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasEST2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasFAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasPRJ.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasSRV.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTRB2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GraficosLoja.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosCOM.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosContab2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosCPR2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosEST2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosFAT2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosFIS.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosLoja.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosPCP.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosPRJ.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RelatoriosSRV.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasAdm2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasCOM.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasContab2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasCPR2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasCRFAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasECF.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasEST2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasFAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasFIS.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasLoja.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasMAT2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasPCP2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasPRJ.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasPV2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasSRV2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\RotinasTRB2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\SGEECF.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\SGEPrinc2.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\Telas2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasAdm2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasCOM.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasCpr2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasECF.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasEST2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasFAT2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasFIS.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasLoja.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasPCP.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasPRJ.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasSRV.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\TelasTRB2.ocx C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\Instalacao2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasCPRAlac.dll C:\Expedicao\Atualizacao\pgm_alacer /Y
xcopy c:\sge\contab\RotinasESTEC.dll C:\Expedicao\Atualizacao\pgm_ec /Y
xcopy c:\sge\contab\ADRel2.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\ADEnviarEmail.dll C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisPVAla.dll C:\Expedicao\Atualizacao\pgm_alacer /Y
xcopy c:\sge\contab\RotinasPVAla.dll C:\Expedicao\Atualizacao\pgm_alacer /Y
xcopy c:\sge\contab\GlobaisTelasFATAla.dll C:\Expedicao\Atualizacao\pgm_alacer /Y
xcopy c:\sge\contab\TelasFATAla.ocx C:\Expedicao\Atualizacao\pgm_alacer /Y
xcopy c:\sge\contab\TelasFATARTX.ocx C:\Expedicao\Atualizacao\pgm_artlux /Y
xcopy c:\sge\contab\SGEECFConfig.exe C:\Expedicao\Atualizacao\pgm_padrao /Y
xcopy C:\SGEUtil\SGEUtil\SGEUtil\bin\Release\*.* c:\expedicao\atualizacao\pgm_padrao /Y
xcopy C:\sgesat\SGESAT_2_5_15\SGESAT_2_5_15\bin\Release\*.* c:\expedicao\atualizacao\pgm_padrao /Y
xcopy C:\sgenfe\sgenfe\sgenfe\bin\Release\*.* c:\expedicao\atualizacao\pgm_padrao /Y
xcopy \\desktop-ludj7jh\c\nfe4\sgenfe4\sgenfe\bin\Release\*.* c:\expedicao\atualizacao\pgm_padrao /Y
xcopy c:\sge\contab\GlobaisTelasFATPan.dll C:\Expedicao\Atualizacao\pgm_panattos /Y
xcopy c:\sge\contab\GlobaisFATBeit.dll C:\Expedicao\Atualizacao\pgm_beit /Y
xcopy c:\sge\contab\RotinasFATBeit.dll C:\Expedicao\Atualizacao\pgm_beit /Y
xcopy c:\sge\contab\TelasFATBeit.ocx C:\Expedicao\Atualizacao\pgm_beit /Y
xcopy rotinasecf.txt  c:\expedicao\atualizacao\pgm_padrao /Y
