xcopy BatchTransfECF.exe  c:\expedicao\atualizacao\pgm_loja /Y
xcopy SGEECF.exe  c:\expedicao\atualizacao\pgm_loja /Y
xcopy GlobaisLoja.dll  c:\expedicao\atualizacao\pgm_loja /Y
xcopy RotinasECF.dll  c:\expedicao\atualizacao\pgm_loja /Y
xcopy TelasECF.ocx  c:\expedicao\atualizacao\pgm_loja /Y
xcopy RotinasLoja.dll  c:\expedicao\atualizacao\pgm_loja /Y
xcopy rotinasecf.txt  c:\expedicao\atualizacao\pgm_loja /Y
xcopy C:\SGEUtil\SGEUtil\SGEUtil\bin\Release\*.* c:\expedicao\atualizacao\pgm_loja /Y
xcopy C:\sgesat\SGESAT_2_5_15\SGESAT_2_5_15\bin\Release\*.* c:\expedicao\atualizacao\pgm_loja /Y
xcopy C:\sgenfe\sgenfe\sgenfe\bin\Release\*.* c:\expedicao\atualizacao\pgm_loja /Y
xcopy \\desktop-ludj7jh\c\nfe4\sgenfe4\sgenfe\bin\Release\*.* c:\expedicao\atualizacao\pgm_loja /Y
xcopy SGEECF.exe  c:\expedicao\atualizacao\pgm_loja\md5 /Y
xcopy RotinasECF.dll  c:\expedicao\atualizacao\pgm_loja\md5 /Y
xcopy TelasECF.ocx  c:\expedicao\atualizacao\pgm_loja\md5 /Y
