VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassImpCoinfoArqBaixa"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public lNumTitulo As Long
Public iNumParcela As Integer
Public dvalor As Double
Public dvalorMulta As Double
Public dvalorJuros As Double
Public dvalorDesconto As Double
Public dvalorRecebido As Double
Public dtData As Date
Public dHora As Double
Public iTipo As Integer
Public lNumIntBaixaParcRec As Long
Public lNumIntTitulo As Long
Public lNumIntParcela As Long
Public sNumCC As String
Public lNumVou As Long

