VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassItemPCDI"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public lNumIntDI As Long
Public iSeq As Integer
Public iFilialEmpresa As Integer

Public lCodigoPC As Long
Public dtDataPC As Date


Public sProdutoPC As String
Public sDescProdPC As String
Public sUMPC As String
Public dQuantPC As Double


