VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassImpCoinfoItemNF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public lNumIntArq As Long
Public scodest As String
Public lNumNF As Long
Public dValor As Double
Public idescacre1 As Integer
Public idescacre2 As Integer
Public idescacre3 As Integer
Public lnumfat As Long
Public sTexto1 As String
Public lordem As Long
Public lcdfilial As Long
Public iExportado As Integer
Public dtDataExp As Date
