VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClassImpCoinfoOcor"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public lNumIntDoc As Long
Public lNumIntArq As Long
Public lnumocorr As Long
Public dtdata As Date
Public dvalor As Double
Public scodest As String
Public susuario As String
Public dtdatareg As Date
Public lrecnsica As Long
Public sTipVou As String
Public sSerie As String
Public lNumVou As Long
Public idc As Integer
Public lCodEmp As Long
Public stexto1 As String
Public stexto2 As String
Public stexto3 As String
Public stexto4 As String
Public stexto5 As String
Public stexto6 As String
Public iliberado As Integer
Public sControle As String
Public lordem As Long
Public iExportado As Integer
Public dtDataExp As Date
