'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe"),  _
 System.Xml.Serialization.XmlRootAttribute("consReciNFe", [Namespace]:="http://www.portalfiscal.inf.br/nfe", IsNullable:=false)>  _
Partial Public Class TConsReciNFe
    
    Private tpAmbField As TAmb
    
    Private nRecField As String
    
    Private versaoField As String
    
    '''<remarks/>
    Public Property tpAmb() As TAmb
        Get
            Return Me.tpAmbField
        End Get
        Set
            Me.tpAmbField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property nRec() As String
        Get
            Return Me.nRecField
        End Get
        Set
            Me.nRecField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property versao() As String
        Get
            Return Me.versaoField
        End Get
        Set
            Me.versaoField = value
        End Set
    End Property
End Class

