Attribute VB_Name = "GlobalLoja"
Option Explicit

Public Const INTEGRACAO_TIPO_NENHUMA = 0
Public Const INTEGRACAO_TIPO_NTK = 1
Public Const INTEGRACAO_TIPO_PP = 2
Public Const INTEGRACAO_TIPO_IFOOD = 3

Public Const STRING_PRODUTO_ICMSALIQUOTA = 2
Public Const STRING_PRODUTO_TRUNCAMENTO = 1

Type typeSize
        cx As Long
        cy As Long
End Type


Public Declare Function BlockInput Lib "user32.dll" (ByVal Blk As Boolean) As Boolean
Public Declare Function SetWindowPos Lib "user32" (ByVal hWnd As Long, ByVal hWndInsertAfter As Long, ByVal X As Long, ByVal Y As Long, ByVal cx As Long, ByVal cy As Long, ByVal wFlags As Long) As Long
Public Declare Function ShowWindow Lib "user32" (ByVal hWnd As Long, ByVal nCmdShow As Long) As Long
Public Declare Sub Sleep Lib "kernel32" (ByVal dwMilliseconds As Long)
Public Declare Function SetActiveWindow Lib "user32" (ByVal hWnd As Long) As Long
Public Declare Function GetTextExtentPoint32 Lib "gdi32" Alias "GetTextExtentPoint32A" (ByVal hdc As Long, ByVal lpsz As String, ByVal cbString As Long, lpSize As typeSize) As Long
Public Declare Function GetSystemMetrics Lib "user32" (ByVal nIndex As Long) As Long
Public Const SM_CXVSCROLL = 2

Public Const STRING_ITEMCFISCAL_SITUACAOTRIB = 10

Public Const IMPRESSORA_DARUMA_FS600 = 6
Public Const IMPRESSORA_NAO_FISCAL = 4
Public Const IMPRESSORA_ELGIN = 7 'ECF IF500 1E
Public Const IMPRESSORA_SAT_2_5_15 = 8
Public Const IMPRESSORA_NFCE = 9
Public Const IMPRESSORA_DARUMA_DR700 = 10
Public Const IMPRESSORA_NFE = 11
Public Const IMPRESSORA_BEMATECH_MP4200_TH_FI = 12
Public Const IMPRESSORA_BEMATECH_MP2100_TH_FI = 13
Public Const IMPRESSORA_BEMATECH_MP4000_TH = 14
Public Const IMPRESSORA_EPSON_TM_T20 = 15
Public Const IMPRESSORA_ELGIN_VOX = 16
Public Const IMPRESSORA_BEMATECH_ESCBEMA = 17
Public Const IMPRESSORA_EPSON_ESCPOS = 18
Public Const IMPRESSORA_DARUMA_ESCPOS = 19

Public Const STRING_MOVIMENTOCAIXA_MSG = 500

Public Const STRING_ORCAMENTO_MSG = 500
Public Const STRING_ORCAMENTO_CNPJ = 14
Public Const STRING_ORCAMENTO_CLINOMERED = 50
Public Const STRING_ORCAMENTO_NUMERODAV = 13
Public Const STRING_ORCAMENTO_EAD = 256


Public Const STRING_D1_CNPJ = 14
Public Const STRING_D1_INSCESTADUAL = 14
Public Const STRING_D1_INSCMUNICIPAL = 14
Public Const STRING_D1_RAZAOSOCIAL = 50
Public Const STRING_D1_EAD = 256


Public Const STRING_D2_CNPJ = 14
Public Const STRING_D2_NUMEROSERIE = 20
Public Const STRING_D2_MFADICIONAL = 1
Public Const STRING_D2_TIPOECF = 7
Public Const STRING_D2_MARCAECF = 20
Public Const STRING_D2_MODELOECF = 20
Public Const STRING_D2_NUMERODAV = 13
Public Const STRING_D2_TITULODAV = 30
Public Const STRING_D2_NOMECLIENTE = 40
Public Const STRING_D2_CNPJCLIENTE = 14
Public Const STRING_D2_EAD = 256


Public Const STRING_D3_CNPJ = 14
Public Const STRING_D3_NUMEROSERIE = 20
Public Const STRING_D3_MFADICIONAL = 1
Public Const STRING_D3_TIPOECF = 7
Public Const STRING_D3_MARCAECF = 20
Public Const STRING_D3_MODELOECF = 20
Public Const STRING_D3_NUMERODAV = 13
Public Const STRING_D3_CODPRODUTO = 14
Public Const STRING_D3_DESCPRODUTO = 100
Public Const STRING_D3_UM = 5
Public Const STRING_D3_SITUACAOTRIBUTARIA = 1
Public Const STRING_D3_INDICADORCANCELAMENTO = 1
Public Const STRING_D3_EAD = 256

Public Const STRING_D4_CNPJ = 14
Public Const STRING_D4_NUMEROSERIE = 20
Public Const STRING_D4_MFADICIONAL = 1
Public Const STRING_D4_TIPOECF = 7
Public Const STRING_D4_MARCAECF = 20
Public Const STRING_D4_MODELOECF = 20
Public Const STRING_D4_NUMERODAV = 13
Public Const STRING_D4_CODPRODUTO = 14
Public Const STRING_D4_DESCPRODUTO = 100
Public Const STRING_D4_UM = 5
Public Const STRING_D4_SITUACAOTRIBUTARIA = 1
Public Const STRING_D4_INDICADORCANCELAMENTO = 1
Public Const STRING_D4_TIPOALTERACAO = 1
Public Const STRING_D4_EAD = 256

Public Const STRING_MEIOPAGAMENTO_MEIOPAGAMENTO = 25
Public Const STRING_MEIOPAGAMENTO_EAD = 256

'constantes da tabela ArquivoECF
Public Const ARQUIVOECF_NOME = 50

'constantes da tabela CONFIGURACAOECF
Public Const CONFECF_CNPJDESENV = 14
Public Const CONFECF_IEDESENV = 18
Public Const CONFECF_IMDESENV = 18
Public Const CONFECF_RAZAOSOCIALDESENV = 50
Public Const CONFECF_NOMEPAFECF = 50
Public Const CONFECF_VERSAOPAFECF = 10
Public Const CONFECF_ENDDESENV = 60
Public Const CONFECF_TELDESENV = 18
Public Const CONFECF_CONTATODESENV = 50
Public Const CONFECF_NUMLAUDO = 10
Public Const CONFECF_VERSAOESPREQPAFECF = 10
Public Const CONFECF_PRINCEXEC = 50
Public Const CONFECF_DIRPAFECF = 128


'constantes do Registro E1 do PAFECF

Public Const E1_CNPJ = 14
Public Const E1_INSCESTADUAL = 14
Public Const E1_INSCMUNICIPAL = 14
Public Const E1_RAZAOSOCIAL = 50
Public Const E1_NUMEROSERIE = 20
Public Const E1_MFADICIONAL = 1
Public Const E1_TIPOECF = 7
Public Const E1_MARCAECF = 20
Public Const E1_MODELOECF = 20

'constantes do Registro E2 do PAFECF

Public Const E2_CODPRODUTO = 14
Public Const E2_DESCRICAO = 50
Public Const E2_UM = 6
Public Const E2_POSITIVONEGATIVO = 1
Public Const E2_CNPJ = 14
Public Const E2_EAD = 256

'constantes do Registro E3 do PAFECF

Public Const E3_NUMEROSERIE = 20
Public Const E3_MFADICIONAL = 1
Public Const E3_TIPOECF = 7
Public Const E3_MARCAECF = 20
Public Const E3_MODELOECF = 20
Public Const E3_EAD = 256


'constantes do Registro P1 do PAFECF

Public Const P1_CNPJ = 14
Public Const P1_INSCESTADUAL = 14
Public Const P1_INSCMUNICIPAL = 14
Public Const P1_RAZAOSOCIAL = 50

'constantes do Registro E2 do PAFECF

Public Const P2_CNPJ = 14
Public Const P2_CODPRODUTO = 14
Public Const P2_DESCRICAO = 50
Public Const P2_UM = 6
Public Const P2_IAT = 1
Public Const P2_IPPT = 1
Public Const P2_SITTRIB = 1
Public Const P2_EAD = 256


'constantes do Registro R01 do PAFECF

Public Const R01_CODNACID = 6
Public Const R01_NUMEROSERIE = 20
Public Const R01_MFADICIONAL = 1
Public Const R01_TIPOECF = 7
Public Const R01_MARCAECF = 20
Public Const R01_MODELOECF = 20
Public Const R01_VERSAOSB = 10
Public Const R01_CNPJUSU = 14
Public Const R01_IEUSU = 14
Public Const R01_CNPJDESENV = 14
Public Const R01_IEDESENV = 14
Public Const R01_IMDESENV = 14
Public Const R01_NOMEDESENV = 40
Public Const R01_NOMEPAFECF = 40
Public Const R01_VERSAOPAFECF = 10
Public Const R01_MD5PAFECF = 32
Public Const R01_VERSAOESPECPAFECF = 4
Public Const R01_EAD = 256
Public Const R01_HORAINSTALACAOSB = 20

'constantes do Registro R02 do PAFECF
Public Const R02_INCIDENCIADESCONTOISS = 1
Public Const R02_EAD = 256
Public Const R02_HORAREDUCAOZ = 20

'constantes do Registro R03 do PAFECF
Public Const R03_TOTALIZADORPARCIAL = 7
Public Const R03_EAD = 256

'constantes do Registro R04 do PAFECF
Public Const R04_TIPODESCONTO = 1
Public Const R04_TIPOACRESCIMO = 1
Public Const R04_INDICADORCANCELAMENTO = 1
Public Const R04_ORDEMDESCACRESC = 1
Public Const R04_NOMEADQUIRENTE = 40
Public Const R04_CPFCNPJ = 14
Public Const R04_EAD = 256

'constantes do Registro R05 do PAFECF
Public Const R05_CODPRODUTO = 14
Public Const R05_DESCPRODUTO = 100
Public Const R05_UM = 6
Public Const R05_TOTALIZADORPARCIAL = 7
Public Const R05_INDICADORCANCELAMENTO = 1
Public Const R05_IAT = 1
Public Const R05_PPT = 1
Public Const R05_EAD = 256

'constantes do Registro R06 do PAFECF
Public Const R06_DENOMINACAO = 2
Public Const R06_EAD = 256
Public Const R06_HORAFINALEMISSAO = 20

'constantes do Registro R07 do PAFECF
Public Const R07_MEIOPAGAMENTO = 15
Public Const R07_INDICADORESTORNO = 1
Public Const R07_EAD = 256

'Versao do Codigo Loja para Leitura e Geracao de Arquivos
Public Const VERSAO_ECF_INICIAL = 302
Public Const VERSAO_ECF = 304
Public Const VERSAO_ECF_303 = 303
Public Const VERSAO_ECF_304 = 304

'Tipos de TEF
Public Const TIPOTEF_SITEF = 1
Public Const TIPOTEF_DISC = 0

'Indica que esta capturando as informacoes de pre autorizacao
Public Const TEF_PRE_AUTORIZACAO_CAPTURA = 1

'Tipos de Transacao TEF Discado
Public Const TIPOTRANS_DISC_ADM = 0
Public Const TIPOTRANS_DISC_FECHA_LOTE = 1
Public Const TIPOTRANS_DISC_CRED_VISTA = 10
Public Const TIPOTRANS_DISC_CRED_PARC_LOJA = 11
Public Const TIPOTRANS_DISC_CRED_PARC_ADM = 12
Public Const TIPOTRANS_DISC_PRE_AUT_CRED = 13
Public Const TIPOTRANS_DISC_DEB_VISTA = 20
Public Const TIPOTRANS_DISC_DEB_PRE = 21
Public Const TIPOTRANS_DISC_DEB_PARCELADO = 22
Public Const TIPOTRANS_DISC_DEB_VISTA_FORCADO = 23
Public Const TIPOTRANS_DISC_DEB_PRE_FORCADA = 24
Public Const TIPOTRANS_DISC_DEB_PRE_SEM_GARANTIA = 25
Public Const TIPOTRANS_DISC_OUTROS_CARTOES = 30
Public Const TIPOTRANS_DISC_CDC = 40
Public Const TIPOTRANS_DISC_CDC_CONSULTA = 41
Public Const TIPOTRANS_DISC_CONVENIO = 50
Public Const TIPOTRANS_DISC_VOUCHER = 60
Public Const TIPOTRANS_DISC_CONSULTA_CHEQUE = 70
Public Const TIPOTRANS_DISC_GARANTIA_CHEQUE = 71
Public Const TIPOTRANS_DISC_OUTRAS = 99


'Tipos de Transacao TEF Sitef

Public Const TIPOTRANS_SITEF_PRE_AUT_CRED = 18
Public Const TIPOTRANS_SITEF_EST_PRE_AUT = 19
Public Const TIPOTRANS_SITEF_CAPTURA_PRE_AUT = 20
Public Const TIPOTRANS_SITEF_EST_CAPTURA_PRE_AUT = 21
Public Const TIPOTRANS_SITEF_CONSULTA_AVS = 22
Public Const TIPOTRANS_SITEF_DEB_MAGN = 32
Public Const TIPOTRANS_SITEF_DEB_FORCADA = 33
Public Const TIPOTRANS_SITEF_DEB_PRE = 34
Public Const TIPOTRANS_SITEF_CANC_DEB = 35
Public Const TIPOTRANS_SITEF_DEB_PARC_CENT = 36
Public Const TIPOTRANS_SITEF_DEB_PARC_SENT = 38
Public Const TIPOTRANS_SITEF_CDC_CONSULTA = 39
Public Const TIPOTRANS_SITEF_CDC = 40
Public Const TIPOTRANS_SITEF_DEB_PARC = 42
Public Const TIPOTRANS_SITEF_CRED_MAGN = 48
Public Const TIPOTRANS_SITEF_CRED_DIG = 50
Public Const TIPOTRANS_SITEF_CANC_CRED_MAGN = 54
Public Const TIPOTRANS_SITEF_CANC_CRED_DIG = 55
Public Const TIPOTRANS_SITEF_CRED_PARC = 56
Public Const TIPOTRANS_SITEF_CONS_PARC_CRED = 63
Public Const TIPOTRANS_SITEF_CONS_GAR_CHQ = 112
Public Const TIPOTRANS_SITEF_CONS_CGC_SERASA = 114
Public Const TIPOTRANS_SITEF_CONS_TELECHEQUE = 116
Public Const TIPOTRANS_SITEF_CANC_GAR_CHQ = 119
Public Const TIPOTRANS_SITEF_OUTRAS_CONSULTAS = 240



Public Const MAX_REPETICOES_ESPERA_FTP = 50

Public Const GRAVACAO_CONCLUIDA = "Gravação concluida com sucesso."
Public Const TRANSMISSAO_INICIADA = "Transmissão iniciada..."
Public Const TRANSMISSAO_CONCLUIDA = "Transmissão concluida com sucesso."
Public Const RECEPCAO_INICIADA = "Recepção iniciada..."
Public Const RECEPCAO_CONCLUIDA = "Recepção concluida com sucesso."
Public Const CARGA_CONCLUIDA = "Carga concluida com sucesso."


Public Const HWND_BOTTOM = 1
Public Const SWP_NOMOVE = &H2
Public Const SWP_NOSIZE = &H1
Public Const SWP_NOACTIVATE = &H10


Public Const SW_SHOWMINNOACTIVE = 7
Public Const SW_SHOWMINIMIZED = 2
Public Const SW_SHOWNOACTIVATE = 4

Public Const TRANSMISSAO_ARQ_BATCH = 1

Public Const VENDEDOR_ECF_MSG = "Vendedor: "

Public Const GERA_ARQ_CCC = 1
Public Const NAO_GERA_ARQ_CCC = 0


Public Const FAZ_REDUCAOZ = 1
Public Const NAO_FAZ_REDUCAOZ = 0

'Categoria de Produto usado para cadastrar limites de descontos por tipo de produto
Public Const LIMITE_DESCONTO = "LIMITEDESCONTO"

'Constantes referentes a LojaConfig
Public Const DIRETORIO_TELA_EXIBIRARQUIVOS = "DIRETORIO_TELA_EXIBIRARQUIVOS"
Public Const DIRETORIO_TELA_EXIBIRARQUIVOSCCBACK = "DIRETORIO_TELA_EXIBIRARQUIVOSCCBACK"

'numero maximo de registros que sao exibidos na tela ExibirSequenciaisCCBack
Public Const NUM_MAX_SEQ_CONTROLELOGCCBACK = 1000

Public Const CLIENTE_CADASTRO_LOJA_STRING = "Loja"
Public Const CLIENTE_CADASTRO_BACK_STRING = "Back"

Public Const TIPO_CLIENTE_LOJA = 9999

Public Const NUM_MAX_LOCK = 50

Public Const CAIXA_NORMAL = 0
Public Const CAIXA_SO_ORCAMENTO = 1

Public Const BORDERO_BOLETO_EXIBE_TELA = 0
Public Const BORDERO_BOLETO_NAO_EXIBE_TELA = 1

Public Const FAZ_TESTE_SALDO = 1

Public Const REDE_ATIVO = 1
Public Const REDE_INATIVO = 0

Public Const ADMMEIOPAGTO_ATIVO = 1
Public Const ADMMEIOPAGTO_INATIVO = 0

Public Const ADMMEIOPAGTOCONDPAGTO_ATIVO = 1
Public Const ADMMEIOPAGTOCONDPAGTO_INATIVO = 0

Public Const ADMMEIOPAGTOCONDPAGTO_PREDATADO = 1
Public Const ADMMEIOPAGTOCONDPAGTO_NAO_PREDATADO = 0


'constantes para Back
Public Const NUM_MAX_CUPONS_EM_TRANS = 100
Public Const NUM_MAX_PRODUTOS_EM_TRANS = 60000

Public Const CAIXA_ATIVO = 1
Public Const CAIXA_INATIVO = 0

Public Const OPERADOR_ATIVO = 1
Public Const OPERADOR_INATIVO = 0

Public Const ECF_ATIVO = 1
Public Const ECF_INATIVO = 0

Public Const TIPOMEIOPAGTOLOJA_EXIGE_REDE = 1
Public Const TIPOMEIOPAGTOLOJA_NAO_EXIGE_REDE = 0

Public Const STATUS_TRANSFERIDO = 1
Public Const STATUS_NAO_TRANSFERIDO = 0

'Constante que indica que está sendo feita a carga do log do caixa central no backoffice - Loja
Public Const CARGA_LOG_BACKOFFICE = 1

'Constantes para inicialização de String dos TiposMovtoCaixa
Public Const STRING_TIPOMOVTOCAIXA_DESCRICAO = 50
Public Const STRING_TIPOMOVTOCAIXA_NOMERED = 50
Public Const STRING_TIPOMOVTOCAIXA_SIGLA = 50
Public Const STRING_TIPOMOVTOCAIXA_SIGN_REF_INT = 50

'constantes que indicam se um caixa possui ou não impressora
Public Const POSSUI_ECF = 1
Public Const NAO_POSSUI_ECF = 0

'constantes que indicam se remove orçamento ao ser convertido para cupom ou nao
Public Const REMOVER_ORC = 1
Public Const NAO_REMOVER_ORC = 0


'Tipo de Referencia
Enum enumTipoProd
    TIPO_PROD_COD_BARRA = 0
    TIPO_PROD_REFERENCIA = 1
End Enum

'tamanho máximo da string
Public Const MAX_TAM_STRING = 65000

'tamanho máximo da string de MovimentoCaixa
Public Const MAX_TAM_STRING_MOVIMENTOCAIXA = 490

Public Const Carne_sCarne = 20

'const da tela transfcentral
'tulio 10/10/02
Public Const NAO_EXCLUSAO = 0
Public Const EXCLUSAO = 1

'???? Movimentos d Caixa
Public Const MOVIMENTOCAIXA_EXCLUIDO = 1
Public Const MOVIMENTOCAIXA_BORDERO_CHEQUE = 2
Public Const MOVIMENTOCAIXA_BORDERO_BOLETO_CC = 3
Public Const MOVIMENTOCAIXA_BORDERO_VALETICKET = 4
Public Const MOVIMENTOCAIXA_RECEB_DINHEIRO = 6
Public Const MOVIMENTOCAIXA_RECEB_CHEQUE = 7
Public Const MOVIMENTOCAIXA_RECEB_CARTAOCREDITO = 8
Public Const MOVIMENTOCAIXA_RECEB_CARTAODEBITO = 9
Public Const MOVIMENTOCAIXA_RECEB_VALETICKET = 10
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_DINHEIRO = 16
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_DINHEIRO = 17
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_CHEQUE = 18
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_CHEQUE = 19
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_CARTAO_CREDITO = 20
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_CARTAO_CREDITO = 21
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_CARTAO_DEBITO = 22
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_CARTAO_DEBITO = 23
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_VALETICKET = 24
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_VALETICKET = 25
Public Const MOVIMENTOCAIXA_TROCO_DINHEIRO = 26
Public Const MOVIMENTOCAIXA_TROCO_CONTRAVALE = 29
Public Const MOVIMENTOCAIXA_TROCO_VALE = 30
Public Const MOVIMENTO_CAIXA_ABERTURA = 31
Public Const MOVIMENTO_CAIXA_FECHAMENTO = 32
Public Const MOVIMENTO_CAIXA_LEITURA_X = 33
Public Const MOVIMENTO_CAIXA_REDUCAO_Z = 34
Public Const MOVIMENTO_CAIXA_SESSAO_ABERTURA = 35
Public Const MOVIMENTO_CAIXA_SESSAO_FECHAMENTO = 36
Public Const MOVIMENTOCAIXA_SUPRIMENTO_DINHEIRO = 37
Public Const MOVIMENTOCAIXA_RECEB_TROCA = 40
Public Const MOVIMENTOCAIXA_RECEB_CARNE = 41
Public Const MOVIMENTOCAIXA_SANGRIA_DINHEIRO = 42
Public Const MOVIMENTOCAIXA_RECEB_OUTROS = 43
Public Const MOVIMENTOCAIXA_SANGRIA_CHEQUE = 45
Public Const MOVIMENTOCAIXA_SANGRIA_BOLETO_CD = 46
Public Const MOVIMENTOCAIXA_EXCLUSAO_SANGRIA_B0LETO = 47
Public Const MOVIMENTOCAIXA_SANGRIA_TICKET = 48
Public Const MOVIMENTOCAIXA_EXCLUSAO_SANGRIA_TICKET = 49
Public Const MOVIMENTOCAIXA_EXCLUSAO_SUPRIMENTO_DINHEIRO = 50
Public Const MOVIMENTOCAIXA_EXCLUSAO_SANGRIA_DINHEIRO = 51
Public Const MOVIMENTOCAIXA_SANGRIA_OUTROS = 52
Public Const MOVIMENTOCAIXA_EXCLUSAO_SANGRIA_OUTROS = 53
Public Const MOVIMENTOCAIXA_CANCELAMENTO_RECEBCARNE = 54
Public Const MOVIMENTOCAIXA_EXCLUSAO_SANGRIA_CHEQUE = 55
Public Const MOVIMENTOCAIXA_RECEB_CARNE_DINHEIRO = 56
Public Const MOVIMENTOCAIXA_RECEB_CARNE_CHEQUE = 57
Public Const MOVIMENTOCAIXA_RECEB_CARNE_CARTAODEBITO = 58
Public Const MOVIMENTOCAIXA_RECEB_CARNE_OUTROS = 59
Public Const MOVIMENTOCAIXA_CARNE_TROCO_DINHEIRO = 60
Public Const MOVIMENTOCAIXA_CARNE_TROCO_CONTRAVALE = 61
Public Const MOVIMENTOCAIXA_CARNE_TROCO_TICKET = 62
Public Const MOVIMENTOCAIXA_ENT_SANGRIA_DINHEIRO = 63
Public Const MOVIMENTOCAIXA_ENT_SANGRIA_CHEQUE = 64
Public Const MOVIMENTOCAIXA_ENT_SANGRIA_BOLETO = 65
Public Const MOVIMENTOCAIXA_ENT_SANGRIA_TICKET = 66
Public Const MOVIMENTOCAIXA_ENT_SANGRIA_OUTROS = 67
Public Const MOVIMENTO_CAIXA_SESSAO_SUSPENSAO = 68
Public Const MOVIMENTO_CAIXA_LEITURA_MEMORIA_FISCAL = 69
Public Const MOVIMENTOCAIXA_SAIDA_TRANSF_OUTROS = 70
Public Const MOVIMENTOCAIXA_ENTRADA_TRANSF_OUTROS = 71
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_DINHEIRO = 72
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_DINHEIRO = 73
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_CHEQUE = 74
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_CHEQUE = 75
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_CARTAO_CREDITO = 76
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_CARTAO_CREDITO = 77
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_CARTAO_DEBITO = 78
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_CARTAO_DEBITO = 79
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_VALETICKET = 80
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_VALETICKET = 81
Public Const MOVIMENTOCAIXA_EXCLUSAO_ENTRADA_TRANSF_OUTROS = 82
Public Const MOVIMENTOCAIXA_EXCLUSAO_SAIDA_TRANSF_OUTROS = 83
Public Const MOVIMENTOCAIXA_BORDERO_OUTROS = 84
Public Const MOVIMENTOCAIXA_SANGRIA_BOLETO_CC = 85
Public Const MOVIMENTOCAIXA_ENTRADA_CHEQUE_ESPECIFICACAO = 86
Public Const MOVIMENTOCAIXA_SAIDA_CHEQUE_ESPECIFICACAO = 87
Public Const MOVIMENTOCAIXA_TRANSF_SUP_DINHEIRO = 88
Public Const MOVIMENTOCAIXA_TRANSF_SUP_CHEQUE = 89
Public Const MOVIMENTOCAIXA_TRANSF_SUP_BOLETO_CC = 90
Public Const MOVIMENTOCAIXA_TRANSF_SUP_TICKET = 91
Public Const MOVIMENTOCAIXA_TRANSF_SUP_OUTROS = 92
Public Const MOVIMENTOCAIXA_BORDERO_BOLETO_CD = 93
Public Const MOVIMENTOCAIXA_BORDERO_CHEQUEPRE = 94
Public Const MOVIMENTOCAIXA_BORDERO_DESC_CHEQUE = 95
Public Const MOVIMENTOCAIXA_BORDERO_DEVOL_CHEQUE = 96
Public Const MOVIMENTOCAIXA_ENVIO_CHEQUES_TERCEIROS = 97
Public Const MOVIMENTOCAIXA_DEVOLUCAO_CHEQUES_TERCEIROS = 98
Public Const MOVIMENTOCAIXA_DAV_RELGER = 99
Public Const MOVIMENTOCAIXA_DAV_ARQUIVO = 100
Public Const MOVIMENTOCAIXA_ESPELHO_MFD = 101
Public Const MOVIMENTOCAIXA_ARQUIVO_MFD = 102
Public Const MOVIMENTOCAIXA_MEIOPAGTO_RELGER = 103
Public Const MOVIMENTOCAIXA_IDENTPAFECF_RELGER = 104
Public Const MOVIMENTOCAIXA_VENDAPERIODO_SPED = 105
Public Const MOVIMENTOCAIXA_VENDAPERIODO_SINTEGRA = 106
Public Const MOVIMENTOCAIXA_PARAMCONFIG_RELGER = 107
Public Const MOVIMENTOCAIXA_ARQUIVO_MF = 108
Public Const MOVIMENTOCAIXA_CANC_RECEB_CARTAOCREDITO = 109
Public Const MOVIMENTOCAIXA_CANC_RECEB_CARTAODEBITO = 110
Public Const MOVIMENTOCAIXA_CANC_RECEB_VALETICKET = 111
Public Const MOVIMENTOCAIXA_CANC_RECEB_OUTROS = 112


''''Public Const MOVIMENTOCAIXA_CARTAO_CREDITO = 8
''''Public Const MOVIMENTOCAIXA_CARTAO_DEBITO = 9

''essa constante indica o intervalo entre os tipos (comum e de exclusao)...
''pode ser utilizada para facilitar as conversoes entre os tipos
''!!! IMPORTANTE, AO ALTERAR QUAISQUER CONSTANTES DE
''MOVIMENTOCAIXA ENTRADA OU SAIDA, VERIFICAR A CONSISTENCIA
''DESSA CONSTANTE...
'código comentado por Rafael Menezes em 11/12/2002 com o consentimento do mário
'essa constante aumentaria a chance de erros no dia em que se quisesse mudar qq outra
'que dependesse dela.
'Public Const MOVIMENTOCAIXA_GAP_DE_EXCLUSAO = 20

Public Const SINAL_IGUAL = "="

Public Const STRING_NAO_DETALHADO = "Não Detalhado"
Public Const STRING_TERMINAL_POS = "POS"
Public Const STRING_TERMINAL_MANUAL = "Manual"
Public Const NUM_MAXIMO_LINHAS_GRID = 50
Public Const STRING_NAO_DETALHADO_CDEBITO = "Debito não detalhado"
Public Const STRING_NAO_DETALHADO_CCREDITO = "Crédito não Detalhado"
Public Const CAIXA_CAIXA_CONFIG = "Caixa"



'Constante para validade de carnê
Public Const CARNE_VALIDO = 1
Public Const CARNE_INVALIDO = 0


'Constantes Realcionadas a Tela de Movimento Cheque
Public Const STRING_ESPECIFICADO = "Detalhado"
Public Const STRING_NAO_ESPECIFICADO = "Não detalhado"

'Constante para alíquota
Public Const ALIQUOTA_ISS = 1
Public Const ALIQUOTA_ICMS = 0

'Constante com o símbolo que indica Truncamento de total.
Public Const LOJA_TRUNCAMENTO = "T"
'Constante com o símbolo que indica Arredondamento de total.
Public Const LOJA_ARREDONDAMENTO = "A"

Public Const TRUNCA_LOJA = 1
Public Const ARREDONDA_LOJA = 0

'Constantes para OperacoesECF
Public Const TAMANHO_BUFFER_SEQUENCIAL = 10
Public Const NOME_ARQUIVO_CAIXA = "CAIXACONFIG.ini"
Public Const NOME_ARQUIVO_ORCAMENTO = "ORCAMENTO.ini"
Public Const TRANSACAO_CAIXA_CONFIG = "Transacao"
Public Const CONSTANTE_ERRO = -1
Public Const NOME_ARQUIVO_ROTINAS = "RotinasECF.txt"
Public Const LEITURA_COMPLETA = 1
Public Const LEITURA_DATAS = 2
Public Const LEITURA_REDUCOES = 3
Public Const LEITURA_SIMPLES = 7
Public Const LEITURA_COO = 8

Public Const MOVIMENTOCAIXA_RECEBIMENTO_CHEQUE = 7

'Constantes de Movimentos de Caixa

'Arquivos de TEF
Public Const ARQUIVO_TEF_TEMP = "c:\PAYGO\Req\IntPos.tmp"    '"c:\Tef_dial\Req\IntPos.tmp"
Public Const ARQUIVO_TEF_REQ = "c:\PAYGO\Req\IntPos.001"  '"c:\Tef_dial\Req\IntPos.001"
Public Const ARQUIVO_TEF_RESP1 = "c:\PAYGO\Resp\IntPos.sts"  '"c:\Tef_dial\Resp\IntPos.sts"
Public Const ARQUIVO_TEF_RESP2 = "c:\PAYGO\Resp\IntPos.001"  '"c:\Tef_dial\Resp\IntPos.001"
Public Const ARQUIVO_TEF_ATIVO = "c:\PAYGO\Resp\Ativo.001"  '"c:\Tef_dial\Resp\Ativo.001"
Public Const ARQUIVO_TEF_IMP = "Imprime.txt"
Public Const ARQUIVO_TEF_RESP2_BACKUP = "c:\PAYGO\backup\IntPos.001" '"c:\backup\IntPos.001"
Public Const DIR_TEF_RESP2_BACKUP = "c:\PAYGO\backup" '"c:\backup"
Public Const DIR_TEF_REQ_BACKUP = "c:\PAYGO\backup\req" '"c:\backup\req"
Public Const ARQUIVO_TEF_REQ_BACKUP = "c:\PAYGO\backup\Req\IntPos.001"  '"c:\Tef_dial\backup\Req\IntPos.001"


'Arquivos SiTEF
Public Const ARQUIVO_SITEF_TEMP = "c:\PAYGO\Req\IntPos.tmp"       '"c:\Client\Req\IntPos.tmp"
Public Const ARQUIVO_SITEF_REQ = "c:\PAYGO\Req\IntPos.001"        ' "c:\Client\Req\IntPos.001"
Public Const ARQUIVO_SITEF_RESP1 = "c:\PAYGO\Resp\IntPos.sts"    '"c:\Client\Resp\IntPos.sts"
Public Const ARQUIVO_SITEF_RESP2 = "c:\PAYGO\Resp\IntPos.001"    '"c:\Client\Resp\IntPos.001"
Public Const ARQUIVO_SITEF_ATIVO = "c:\PAYGO\Resp\Ativo.001"    '"c:\Client\Resp\Ativo.001"
Public Const ARQUIVO_SITEF_IMP = "Imprime.txt"
Public Const ARQUIVO_SITEF_RESP2_BACKUP = "c:\PAYGO\backup\IntPos.001" '"c:\Client\backup\IntPos.001"
Public Const DIR_SITEF_RESP2_BACKUP = "c:\PAYGO\backup"  '"c:\Client\backup"
Public Const DIR_SITEF_REQ_BACKUP = "c:\PAYGO\backup\req" '"c:\Client\backup\req"
Public Const ARQUIVO_SITEF_REQ_BACKUP = "c:\PAYGO\backup\Req\IntPos.001" '"c:\Client\backup\Req\IntPos.001"
Public Const DIR_SITEF_REQ_BACKUP1 = "c:\PAYGO\backup1" '"c:\Client\backup1"
Public Const ARQUIVO_SITEF_REQ_BACKUP1 = "c:\PAYGO\backup1\IntPos.001" '"c:\Client\backup1\IntPos.001"
Public Const ARQUIVO_SITEF_REQ_BACKUP2 = "c:\PAYGO\backup1\IntPos.002" '"c:\Client\backup1\IntPos.002"


'Constante para VendaM e VendaP
Public Const TRACO_CAB = "------------------------------------------------"
Public Const TRACO_CAB2 = "-----------------------------------------"
Public Const TIPO_TEF = 2
Public Const TIPO_POS = 1
Public Const TIPO_MANUAL = 0

'Constantes relacionadas à tela BorderoBoleto
Public Const PARCELAMENTO_PARCELADO = 2
Public Const PARCELAMENTO_AMBOS = 3
Public Const JUROSPARCELAMENTO_LOJA = 1
Public Const JUROSPARCELAMENTO_ADM = 2
Public Const BOLETO_MANUAL = 0
Public Const BOLETO_POS = 1
Public Const BOLETO_TEF = 2
Public Const STRING_BORDEROBOLETO_NUMERO = 10

'Constantes Relacionadas a Tela de OperacoesECF
Public Const STATUS_CAIXA_ABERTO = 1
Public Const STATUS_CAIXA_FECHADO = 0
Public Const AUTORIZACAO_GERENTE = 1
Public Const LEITURA_MEMORIAFISCAL_TIPO_TODOS = 0
Public Const LEITURA_MEMORIAFISCAL_TIPO_DATAS = 1
Public Const LEITURA_MEMORIAFISCAL_TIPO_REDUCAO = 2

Public Const STATUS_TIPOCARTAO_MANUAL = 0
Public Const STATUS_TIPOCARTAO_POS = 1
Public Const STATUS_TIPOCARTAO_TEF = 2

Public Const SESSAO_ABERTA = 2
Public Const SESSAO_SUSPENSA = 1
Public Const SESSAO_ENCERRADA = 0

Public Const SESSAO_ABERTA_STRING = "Aberta"
Public Const SESSAO_SUSPENSA_STRING = "Suspensa"
Public Const SESSAO_ENCERRADA_STRING = "Encerrada"


'Constantes para Tipos de registros
Public Const TIPOREGISTROECF_PRODUTOSCODBARRAS = 1
Public Const TIPOREGISTROECF_VENDEDORES = 2
Public Const TIPOREGISTROECF_MEIOSPAGAMENTOS = 3
Public Const TIPOREGISTROECF_OPERADORES = 4
Public Const TIPOREGISTROECF_CONFIGURACAOLOJA = 5
Public Const TIPOREGISTROECF_CAIXAS = 6
Public Const TIPOREGISTROECF_ECF = 7
Public Const TIPOREGISTROECF_TECLADOS = 8
Public Const TIPOREGISTROECF_REDES = 9
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA = 10
Public Const TIPOREGISTROECF_PRODUTOSREFERENCIA = 11
Public Const TIPOREGISTROECF_VENDAS = 12
Public Const TIPOREGISTROECF_SANGRIACHEQUE = 13
Public Const TIPOREGISTROECF_TIPOSMEIOSPAGAMENTOS = 14
Public Const TIPOREGISTROECF_EXCLUSAOORCAMENTO = 15
Public Const TIPOREGISTROECF_SISTEMA = 16
Public Const TIPOREGISTROECF_ENCERRASEQ = 17
Public Const TIPOREGISTROECF_ABRESEQ = 18
Public Const TIPOREGISTROECF_CLIENTE = 19
Public Const TIPOREGISTROECF_CHEQUE = 20
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA_OUTROS = 21
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA_CHEQUES = 22
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA_TICKETS = 23
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA_DINHEIRO = 24
Public Const TIPOREGISTROECF_MOVIMENTOCAIXA_BOLETO = 25
Public Const TIPOREGISTROECF_TRANSFCAIXA_INCLUSAO = 26
Public Const TIPOREGISTROECF_TRANSFCAIXA_EXCLUSAO = 27
Public Const TIPOREGISTROECF_ROLLBACKSEQ = 28
Public Const TIPOREGISTROECF_ABERTURACAIXA = 29
Public Const TIPOREGISTROECF_FECHAMENTOCAIXA = 30
Public Const TIPOREGISTROECF_ALIQUOTAS = 31
Public Const TIPOREGISTROECF_PRODUTOSNOME = 32
Public Const TIPOREGISTROECF_TABELAPRECO = 33
Public Const TIPOREGISTROECF_PRODUTODESCONTO = 34
Public Const TIPOREGISTROECF_TABELAPRECOITENS = 35
Public Const TIPOREGISTROECF_ARQUIVO = 36
Public Const TIPOREGISTROECF_TRANSFERENCIA_SUPRIMENTO = 37
Public Const TIPOREGISTROECF_UNIDADE_MEDIDA = 38
Public Const TIPOREGISTROECF_BANCO = 39
Public Const TIPOREGISTROECF_CCI = 40
Public Const TIPOREGISTROECF_PRODUTO_CATEGORIA = 41
Public Const TIPOREGISTROECF_CATEGORIA_PRODUTO_ITEM = 42
Public Const TIPOREGISTROECF_PAFECF_SPEDFISCAL = 43
Public Const TIPOREGISTROECF_PAFECF_SINTEGRA = 44
Public Const TIPOREGISTROECF_EXCLUSAOCUPOM = 45

'Constantes para LojaConfig
Public Const STRING_LOJACONFIG_CODIGO = 50
Public Const STRING_LOJACONFIG_DESCRICAO = 150
Public Const STRING_LOJACONFIG_CONTEUDO = 255

'Constantes para ECFConfig
Public Const STRING_ECFCONFIG_CODIGO = 50
Public Const STRING_ECFCONFIG_DESCRICAO = 150
Public Const STRING_ECFCONFIG_CONTEUDO = 50

'AdmMeioPagto pre-cadastrados
Public Const MEIO_PAGAMENTO_DINHEIRO = 1
Public Const MEIO_PAGAMENTO_CHEQUE = 2
Public Const MEIO_PAGAMENTO_CONTRAVALE = 3
Public Const MEIO_PAGAMENTO_CARNE = 4
Public Const MEIO_PAGAMENTO_TROCA = 5

'Para CondPagto do ADM
Public Const STRING_ADMMEIOPAGTOCONDPAGTO_NOME = 20

'Erro de Afrac
Public Const ERRO_AFRAC_EXISTE_CUPOM = 9

'Constantes Relacionadas a Tela de Operador
Public Const LOGIN_APENAS_GERENTE = 1
Public Const LOGIN_OPERADOR_SUSPENSO = 2
Public Const LOGIN_TODOS_OPERADORES = 3
Public Const OPERADOR_GERENTE = 1

'Constantes para arquivos
Public Const NOME_ARQUIVOBACK = "DADOSBACK.bcc"
Public Const NOME_ARQUIVOBACK_TEMP = "DADOSBACK.tmp"
Public Const NOME_ARQUIVOCC = "DADOSCC.ccc"
Public Const NOME_ARQUIVOCC_TEMP = "DADOSCC.tmp"
Public Const APLICACAO_CAIXA = "Caixa"
Public Const APLICACAO_SESSAO = "Sessao"
Public Const APLICACAO_TRANSACAO = "Transacao"
Public Const APLICACAO_ECF = "ECF"
Public Const APLICACAO_EMPRESA = "EMPRESA"
Public Const APLICACAO_ARQUIVO = "ARQUIVO"
Public Const APLICACAO_ORCAMENTO = "ORCAMENTO"
Public Const APLICACAO_DADOS = "DADOS"
Public Const APLICACAO_CODBARRAS = "LeitoraCodigoBarras"
Public Const APLICACAO_LOJA = "Loja"
Public Const APLICACAO_RSA = "RSA"
Public Const APLICACAO_PAFECF = "PAFECF"

'Status das operacoes TEF
Public Const TEF_STATUS_VENDA = "1"
Public Const TEF_STATUS_VENDA_VINCULADA = "2"
Public Const TEF_STATUS_VENDA_GERENCIAL = "3"

Public Const TEF_CANCELAMENTO = "1" 'indica que ha comprovantes de cancelamento a imprimir
Public Const TEF_CANCELAMENTO_IMPRESSAO = "2" 'indica que so esta imprimindo os cancelamentos

'constantes para a tela de vendaM
Public Const KEYCODE_VENDEDOR = vbKeyF2
Public Const KEYCODE_PRODUTOS = vbKeyF3
Public Const KEYCODE_CANCELAANTERIOR = vbKeyF4
Public Const KEYCODE_PRECO = vbKeyF5
Public Const KEYCODE_CANCELAITEM = vbKeyF6
Public Const KEYCODE_SUSPENDER = vbKeyF7
Public Const KEYCODE_ORCAMENTO = vbKeyF8
Public Const KEYCODE_FECHAR = vbKeyF9
Public Const KEYCODE_ABRIRGAVETA = vbKeyPageUp
Public Const KEYCODE_CANCELCUPOM = vbKeyEscape
Public Const KEYCODE_PAGAMENTO = vbKeyInsert
'Public Const ITEM_CANCELADO = 1
'Public Const ITEM_NORMAL = 0
Public Const OPTION_CF = 1
Public Const OPTION_PREVENDA = 2
Public Const OPTION_DAV = 3
Public Const QUANTIDADE_DEFAULT = 1
Public Const OPTION_ORCAMENTO = 2

'Constantes para a tela
Public Const BORDERO_TRANSF_BACKOFFICE = 0

'Constantes para a tela DepositoBancario
Public Const STRING_CONTASCORRENTESINTERNAS_AGENCIA = 5
Public Const STRING_CONTASCORRENTESINTERNAS_CONTACONTABIL = 20
Public Const STRING_CONTASCORRENTESINTERNAS_CONTATO = 50
Public Const STRING_CONTASCORRENTESINTERNAS_DESCRICAO = 50
Public Const STRING_CONTASCORRENTESINTERNAS_DVAGCONTA = 1
Public Const STRING_CONTASCORRENTESINTERNAS_DVAGENCIA = 1
Public Const STRING_CONTASCORRENTESINTERNAS_DVNUMCONTA = 1
Public Const STRING_CONTASCORRENTESINTERNAS_FAX = 18
Public Const STRING_CONTASCORRENTESINTERNAS_NOMEREDUZIDO = 15
Public Const STRING_CONTASCORRENTESINTERNAS_NUMCONTA = 12
Public Const STRING_CONTASCORRENTESINTERNAS_TELEFONE = 18
Public Const MOVIMENTO_CAIXA_DEPOSITO_BANCARIO = 27


'Constantes para a tela DepositoCaixa
Public Const MOVIMENTO_CAIXA_DEPOSITO_DINHEIRO = 5
Public Const STRING_CAIXA_CENTRAL = "Central"

'Constantes para tela SaqueCaixa
Public Const MOVIMENTO_CAIXA_SAQUE = 1
Public Const STRING_MOVIMENTOCAIXA_HISTORICO = 50
Public Const STRING_MOVIMENTOCAIXA_FAVORECIDO = 50
Public Const PARCELAMENTO_AVISTA = 1


'Cosntante para Inicilalização de Parcelas

Public Const NOME_A_VISTA = "À Vista"
Public Const JUROS_LOJA = 1


'Constantes para o Teclado
Public Const STRING_TECLADO_DESCRICAO = 30
Public Const STRING_TECLADOPRODUTO_DESCRICAO = 50
Public Const STRING_TECLADOPRODUTOITENS_PRODUTO = 20
Public Const STRING_TECLADOPRODUTOITENS_TITULO = 20
Public Const STRING_TECLADOPRODUTOITENS_ARVOREKEY = 11
Public Const COR_DEFAULT = -2147483633
Public Const TECLADO_PADRAO = 1
Public Const TECLADO_COMUM = 0

'Constantes referentes a tabela TIPOOPLOG
Public Const INCLUSAO_SAQUE_CAIXA_CENTRAL = 1
Public Const ALTERACAO_SAQUE_CAIXA_CENTRAL = 2
Public Const EXCLUSAO_SAQUE_CAIXA_CENTRAL = 3
Public Const INCLUSAO_ADMMEIOPAGTO_CAIXA_CENTRAL = 4
Public Const ALTERACAO_ADMMEIOPAGTO_CAIXA_CENTRAL = 5
Public Const EXCLUSAO_ADMMEIOPAGTO_CAIXA_CENTRAL = 6
Public Const INCLUSAO_DEPOSITO_BANCARIO = 7
Public Const ALTERACAO_DEPOSITO_BANCARIO = 8
Public Const EXCLUSAO_DEPOSITO_BANCARIO = 9
Public Const INCLUSAO_DEPOSITO_CAIXA_CENTRAL = 10
Public Const ALTERACAO_DEPOSITO_CAIXA_CENTRAL = 11
Public Const EXCLUSAO_DEPOSITO_CAIXA_CENTRAL = 12
Public Const INCLUSAO_CHEQUE = 13
Public Const EXCLUSAO_CHEQUE = 14
Public Const ALTERACAO_CHEQUE = 15
Public Const INCLUSAO_REDE_CAIXA_CENTRAL = 19
Public Const ALTERACAO_REDE_CAIXA_CENTRAL = 20
Public Const EXCLUSAO_REDE_CAIXA_CENTRAL = 21
Public Const INCLUSAO_CAIXA = 22
Public Const ALTERACAO_CAIXA = 23
Public Const EXCLUSAO_CAIXA = 24
Public Const INCLUSAO_BORDEROCHEQUE = 25
Public Const EXCLUSAO_BORDEROCHEQUE = 26
Public Const ALTERACAO_BORDEROCHEQUE = 27
Public Const INCLUSAO_ECF_CAIXA_CENTRAL = 28
Public Const ALTERACAO_ECF_CAIXA_CENTRAL = 29
Public Const EXCLUSAO_ECF_CAIXA_CENTRAL = 30
Public Const INCLUSAO_OPERADOR_CAIXA_CENTRAL = 31
Public Const ALTERACAO_OPERADOR_CAIXA_CENTRAL = 32
Public Const EXCLUSAO_OPERADOR_CAIXA_CENTRAL = 33
Public Const INCLUSAO_BORDEROBOLETO = 34
Public Const EXCLUSAO_BORDEROBOLETO = 35
Public Const ALTERACAO_BORDEROBOLETO = 36
Public Const INCLUSAO_BORDEROVALETICKET = 37
Public Const EXCLUSAO_BORDEROVALETICKET = 38
Public Const ALTERACAO_BORDEROVALETICKET = 39
Public Const INCLUSAO_TECLADO_CAIXA_CENTRAL = 41
Public Const ALTERACAO_TECLADO_CAIXA_CENTRAL = 42
Public Const EXCLUSAO_TECLADO_CAIXA_CENTRAL = 43
Public Const INCLUSAO_TECLADO_CONFIGURACAO_CAIXA_CENTRAL = 44
Public Const ALTERACAO_TECLADO_CONFIGURACAO_CAIXA_CENTRAL = 45
Public Const EXCLUSAO_TECLADO_CONFIGURACAO_CAIXA_CENTRAL = 46
Public Const INCLUSAO_BORDEROOUTROS = 47
Public Const EXCLUSAO_BORDEROOUTROS = 48
Public Const ALTERACAO_BORDEROOUTROS = 49
Public Const SANGRIA_DINHEIRO = 57
Public Const SANGRIA_CHEQUE = 58
Public Const SANGRIA_BOLETO = 59
Public Const SANGRIA_TICKET = 60
Public Const SANGRIA_OUTROS = 61
Public Const ABERTURA_CAIXA = 62
Public Const FECHAMENTO_CAIXA = 63
Public Const LEITURA_X = 64
Public Const REDUCAO_Z = 65
Public Const ABERTURA_SESSAO = 66
Public Const SUSPENSAO_SESSAO = 67
Public Const FECHAMENTO_SESSAO = 68
Public Const EXCLUSAO_SANGRIA_DINHEIRO = 69
Public Const INCLUSAO_CUPOM_FISCAL = 70
Public Const LEITURA_MEMORIA_FISCAL = 71
Public Const INCLUSAO_TRANSFERENCIA_CENTRAL = 72 'Inclusão de Transferência de Caixa Central
Public Const EXCLUSAO_TRANSFERENCIA_CENTRAL = 73 'Exclusão de Transferência de Caixa Central
Public Const ALTERACAO_TRANSFERENCIA_CENTRAL = 74 'Alteração de Transferência de Caixa Central
Public Const INCLUSAO_RECEBIMENTOCARNE = 75
Public Const EXCLUSAO_RECEBIMENTOCARNE = 76
Public Const SUPRIMENTO_DINHEIRO = 77
Public Const EXCLUSAO_SUPRIMENTO_DINHEIRO = 80
Public Const EXCLUSAO_CUPOM_FISCAL = 81
Public Const INCLUSAO_IMPRESSORAECF = 82
Public Const ALTERACAO_IMPRESSORAECF = 83
Public Const EXCLUSAO_IMPRESSORAECF = 84
Public Const INCLUSAO_TRANSFERENCIA_CAIXA = 85 'Inclusão de Transferência de Caixa
Public Const EXCLUSAO_TRANSFERENCIA_CAIXA = 86 'Exclusão de Transferência de Caixa
Public Const ESPECIFICACAO_CHEQUE = 87 'Cheques nao especificados sendo especificados pela tela de ChequeNEsp


'Constante CheckBox Marcada/Desmarcada
Public Const CHECK_DESMARC = 0
Public Const CHECK_MARCADA = 1

'Constante Relacionados aos Frames Endereços e Bancos

Public Const ENVIO_ENDERECO = 1
Public Const ENVIO_BANCO = 0

'Contantes Realcionadas a PossuirAdm ou Não
Public Const POSSUI_ADM = 1
Public Const NAO_POSSUI_ADM = 0

'Constante Relacionadas a AdmMeioPagtoCondPagto
Public Const JUROS_ADM = 2

'Constante Inicilazição de Buffer para Validação Em Tabelas
Public Const CODIGO_ADMMEIOPAGTO = 2

'Constantes Relacionadas a Strings
Public Const STRING_NOME_PARCELAMENTO = 20

'Const Relacionadas a Impressoras para acesso a Banco de Dados, Inicialização do Buffer, Tamanho da String
Public Const STRING_IMPRESSORA_NOME = 20

Public Const TIPOMEIOPAGTO_VALETICKETDESCRICAO = "Vale/Ticket"
Public Const TIPOMEIOPAGTO_CARTAOCREDITODESCRICAO = "Cartão de Crédito"
Public Const TIPOMEIOPAGTO_CARTAODEBITODESCRICAO = "Cartão de Débito"

Public Const STRING_FABRICANTE_NOME = 20

Public Const IMPRESSORA_PRESENTE = 1
Public Const IMPRESSORA_AUSENTE = 0

Public Const NAO_TEM_TEF = 0
Public Const TEF_MANUAL = 1
Public Const TEF_ELETRONICO = 2

Public Const HORARIO_VERAO_ATIVO = 1

'Caixa
Public Const CAIXA_COMUM = 0
Public Const CAIXA_CENTRAL = 1
Public Const LEITORA_NAO_PRESENTE = 0
Public Const LEITORA_PRESENTE = 1
Public Const CAIXA_STATUS_FECHADO = 0
Public Const CAIXA_STATUS_ABERTO = 1
Public Const CAIXA_SEM_MOVIMENTO = 0
Public Const CAIXA_COM_MOVIMENTO = 1

Public Const NUM_MAX_ALIQUOTAS = 9
Public Const NUM_MAX_ALIQUOT = 10
Public Const NUM_MAX_CONDPAGTOS = 100


Public Const STRING_ALIQUOTASICMS_SIGLA = 2
Public Const STRING_SIGLA = 2
Public Const STRING_CAIXA_NOME_REDUZIDO = 15
Public Const STRING_CAIXA_DESCRICAO = 50
''''Public Const STRING_CAIXA_CONTA_CONTABIL = 20
Public Const STRING_PRODUTO_CODIGO_REFERENCIA = 10
Public Const STRING_POS_CODIGO = 10
Public Const STRING_REDE_NOME = 20
Public Const STRING_REDE_ESTABELECIMENTO = 20
Public Const STRING_REDE_DIRIMPORTACAOEXTRATO = 255
Public Const STRING_ADMMEIOPAGTO_CODIGO = 2
Public Const STRING_ADMMEIOPAGTO_NOME = 50
Public Const STRING_ADMMEIOPAGTO_NOMETEF = 12
Public Const STRING_ADMMEIOPAGTO_AGENCIA = 6
Public Const STRING_CONDPAGTOADM_DESCREDUZIDA = 30
Public Const STRING_TIPOMEIOPAGTOLOJA_DESCRICAO = 50

'?? Colocar os outros fabricantes ....
Public Const FAB_BEMATECH = 1
Public Const FAB_SWEDA = 3

'Redes
Public Const REDE_TECBAN = 0
Public Const REDE_ITAU = 0
Public Const REDE_BRADESCO = 0
Public Const REDE_VISANET = 1
Public Const REDE_REDECARD = 2
Public Const REDE_AMEX = 3
Public Const REDE_SOLLO = 0
Public Const REDE_DINERS = 0
Public Const REDE_SERASA = 0
Public Const REDE_PAO_DE_ACUCAR = 0
Public Const REDE_SERASA_DETALHADO = 0
Public Const REDE_TELEDATA = 0
Public Const REDE_CERTIF = 8




'Tipos de meio de pagamento Loja
Public Const TIPOMEIOPAGTOLOJA_DINHEIRO = 1
Public Const TIPOMEIOPAGTOLOJA_CHEQUE = 2
Public Const TIPOMEIOPAGTOLOJA_TROCA = 3
Public Const TIPOMEIOPAGTOLOJA_VALE_TICKET = 4
Public Const TIPOMEIOPAGTOLOJA_CARTAO_CREDITO = 5
Public Const TIPOMEIOPAGTOLOJA_CARTAO_DEBITO = 6
Public Const TIPOMEIOPAGTOLOJA_CARNE = 7
Public Const TIPOMEIOPAGTOLOJA_OUTROS = 8
Public Const TIPOMEIOPAGTOLOJA_TEF = 9
Public Const TIPOMEIOPAGTOLOJA_TEFCHQ = 10
Public Const TIPOMEIOPAGTOLOJA_VALE_REFEICAO = 11
Public Const TIPOMEIOPAGTOLOJA_VALE_PRESENTE = 12
Public Const TIPOMEIOPAGTOLOJA_VALE_COMBUSTIVEL = 13
Public Const TIPOMEIOPAGTOLOJA_TROCO = 14

'Tipos de Relatorio Gerencial
Public Const RELGER_SANGRIA_CHEQUE = 2
Public Const RELGER_SANGRIA_TICKET = 3
Public Const RELGER_SANGRIA_CARTAO_CREDITO = 4
Public Const RELGER_SANGRIA_OUTROS = 5
Public Const RELGER_ORCAMENTO = 6
Public Const RELGER_SANGRIASUPRIMENTO_DINHEIRO = 7
Public Const RELGER_COMPROVANTE_TEF = 8
Public Const RELGER_DAV = 9
Public Const RELGER_MEIOPAGAMENTO = 10
Public Const RELGER_IDENTPAFECF = 11
Public Const RELGER_PARAMCONFIG = 12
Public Const RELGER_SAT = 13
Public Const RELGER_NFCE = 14
Public Const RELGER_NFE = 15
Public Const RELGER_SAT_CANC = 16
Public Const RELGER_NFCE_CANC = 17
Public Const RELGER_PEDIDO_NTK = 18
Public Const RELGER_TESTE_IMPRESSAO = 19

'Tipos de Relatorio Gerencial
Public Const RELGER_DESC_SANGRIA_CHEQUE = "SANGRIA CHEQUE"
Public Const RELGER_DESC_SANGRIA_TICKET = "SANGRIA TICKET"
Public Const RELGER_DESC_SANGRIA_CARTAO_CREDITO = "SANGRIA CARTAO"
Public Const RELGER_DESC_SANGRIA_OUTROS = "SANGRIA OUTROS"
Public Const RELGER_DESC_ORCAMENTO = "ORÇAMENTO"
Public Const RELGER_DESC_SANGRIASUPRIMENTO_DINHEIRO = "SANGRIA"
Public Const RELGER_DESC_COMPROVANTE_TEF = "Transf Elet"
Public Const RELGER_DESC_DAV = "Doc Aux Venda"
Public Const RELGER_DESC_MEIOPAGAMENTO = "Meios Pagamento"
Public Const RELGER_DESC_IDENTPAFECF = "Ident. PAF-ECF"
Public Const RELGER_DESC_PARAMCONFIG = "Param. Config."
Public Const RELGER_DESC_SAT = "Sat Cfe"
Public Const RELGER_DESC_NFCE = "NF Cons Elet ."
Public Const RELGER_DESC_NFE = "NF Elet"
Public Const RELGER_DESC_SAT_CANC = "SAT CANCELAMENTO"
Public Const RELGER_DESC_NFCE_CANC = "NFCE CANCELAMENTO"
Public Const RELGER_DESC_PEDIDO_NTK = "PEDIDO NTK"

'Variáveis que armazenam independente de instância da classe
Public LojaGlob_objLoja As ClassLoja
Public LojaGlob_Refs As Integer

'Constantes inseridas por Leo em 31/05/02
Public Const CODIGO_CAIXA_CENTRAL = 9999
Public Const STRING_CAIXA_POS = 10
Public Const CAIXA_ACEITA_BOLETO_MANUAL = 1
Public Const CAIXA_NAO_ACEITA_BOLETO_MANUAL = 0
Public Const CAIXA_ACEITA_POS = 1
Public Const CAIXA_NAO_ACEITA_POS = 0
Public Const CAIXA_ACEITA_TEF = 1
Public Const CAIXA_NAO_ACEITA_TEF = 0

'dados tef
Public Const ABRE_TEF = 0
Public Const DADOS_TEF = 1
Public Const FECHA_TEF = 2
Public Const CANCELA_TEF = 3

'Impressora ECF
Public Const STRING_IMPRESSORAECF_NUMSERIE = 50
Public Const STRING_MODELOECF_NOME = 20
Public Const STRING_MODELOECF_FABRICANTE = 50

'Rede
'Constantes da Tela
Public Const EXISTE_TEF = 1
Public Const NAO_EXISTE_TEF = 0

'Tela de Operador


Public Const VENDEDOR_ATIVO = 1
Public Const STRING_OPERADOR_NOME = 50
Public Const STRING_OPERADOR_SENHA = 10

'Constantes para inicialização de Buffer de Variáveis
Public Const STRING_CONTACORRENTE = 14
Public Const STRING_CPFCGC = 14
Public Const STRING_MOTIVOCANCEL = 50
Public Const STRING_HISTORICO1 = 50

'Contantes pra o grid de parcelas
Public Const NUM_MAXIMO_PARC = 50

'Contantes pra o grid de ticket (TrocoTicket)
Public Const NUM_MAXIMO_TICKET = 50

'Contantes pra o grid de CARTÕES (PagamentoTroca)
Public Const NUM_MAXIMO_CARTOES = 50

'Contantes pra o grid de troca (PagamentoTroca)
Public Const NUM_MAXIMO_TROCA = 50

'Contantes pra o grid de Outros (PagamentoOutros)
Public Const NUM_MAXIMO_OUTROS = 50

'Contantes pra o grid de Cheques (PagamentoCheques)
Public Const NUM_MAXIMO_CHEQUES = 50

'Constantes relaicionadas com a Tela de cheque
Public Const BORDERO_CAIXA_CENTRAL = 0
Public Const CHEQUE_NAO_ESPECIFICADO = 0
Public Const CHEQUE_ESPECIFICADO = 1
Public Const STRING_CPFCGC1 = 50


Public Const STRING_CODNACID_MARCAECF = 20
Public Const STRING_CODNACID_MODELOECF = 20
Public Const STRING_CODNACID_VERSAOSBECF = 20
Public Const STRING_CODNACID_IDENTIFICACAOECF = 20


'Constante para Carne
Public Const STRING_CARNE_CODBARRASCARNE = 20

Type typeTMPLojaFilial

    iFilialEmpresa As Integer
    iTipo As Integer
    dSaldo As Double

End Type




'Inicio dos Types

Type typeTeclado
    iCodigo As Integer
    iFilialEmpresa As Integer
    sDescricao As String
End Type

Type typeAdmMeioPagto
    iCodigo As Integer
    iFilialEmpresa As Integer
    sNome As String
    dTaxaVista As Double
    dTaxaParcelado As Double
    iTipoMeioPagto As Long
    iDefasagemPagtoVista As Integer
    iGeraTituloRec As Integer
    lEndereco As Long
    iCodBanco As Integer
    sAgencia As String
    iContaCorrenteInterna As Integer
    iRede As Integer
    iAtivo As Integer
    dtDataLog As Date
    iProxCodParcelamento As Integer
End Type

Type typeAliquotaICMS
    iFilialEmpresa As Integer
    sSigla As String
    dAliquota As Double
    iISS As Integer
End Type

Type typeBaixaBoletoParcela
    lNumIntDoc As Long
    lNumIntBaixaBoletosParcelas As Long
    lNumIntBoletoParcela As Long
    iStatus As Integer
    dtDataCancelamento As Date
End Type

Type typeBaixaBoletosParcelas
    lNumIntBaixa As Long
    iStatus As Integer
    sHistorico As String
    iMotivo As Integer
    dtData As Date
    dtDataContabil As Date
    dtDataRegistro As Date
    lNumMovCta As Long
End Type

Type typeBaixaValesTickets
    lNumIntBaixa As Long
    iStatus As Integer
    sHistorico As String
    iMotivo As Integer
    dtData As Date
    dtDataContabil As Date
    dtDataRegistro As Date
    lNumMovCta As Long
End Type

Type typeBaixaValeTicket
    lNumIntDoc As Long
    lNumIntBaixaValesTickets As Long
    lNumIntValeTicket As Long
    iStatus As Integer
    dtDataCancelamento As Date
End Type

Type typeBoleto
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    iECF As Integer
    iOperador As Integer
    dtDataTransacao As Date
    sAdmMeioPagto As String
    iTipo As Integer
    sTipoTransacao As String
    sPOS As String
    sNSU As String
    sLote As String
    sAutorizacao As String
    dValor As Double
    iNumParcelas As Integer
    iTipoParcelamento As Integer
    lBordero As Long
    lFechamento As Long
    iStatus As Integer
End Type

Type typeBoletoParcela
    lNumIntDoc As Long
    lNumIntBoleto As Long
    iSequencial As Integer
    sNSU As String
    dValor As Double
    dValorRecebido As Double
    dtDataVencimento As Date
    iStatus As Integer
End Type

Type typeBorderoBoleto
    iFilialEmpresa As Integer
    lNumBordero As Long
    sNumero As String
    dtDataImpressao As Date
    dtDataEnvio As Date
    dtDataBackoffice As Date
    iExibeTela As Integer
    iCodigoRede As Integer
    sNomeRede As String
End Type

Type typeBorderoBoletoItem
    iFilialEmpresa As Integer
    lNumIntDoc As Long
    iAdmMeioPagto As Integer
    dValor As Double
    iParcelamento As Integer
    lNumBordero As Long
    lNumIntDocCPR As Long
    dSaldo As Double
    sNomeParcelamento As String
    sNomeAdmMeioPagto As String
    lNumMovtoCx As Long
End Type

Type typeBorderoCheque
    iFilialEmpresa As Integer
    lNumBordero As Long
    iCodNossaConta As Integer
    dValorEspec As Double
    dValorNEspec As Double
    dtDataImpressao As Date
    dtDataEnvio As Date
    dtDataBackoffice As Date
    lNumMovtoCx As Long
End Type

Type typeBorderoValeTicket
    iAdmMeioPagto As Integer
    iParcelamento As Integer
    dtDataBackoffice As Date
    dValor As Double
    dValorN As Double
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    lCodigo As Long
    sAdmMeioPagto As String
    dtDataEnvio As Date
    dtDataImpressao As Date
    lNumBordero As Long
    lNumIntDocCPR As Long
    lNumMovtoCx As Long
End Type

Type typeBorderoOutros
    iAdmMeioPagto As Integer
    iParcelamento As Integer
    iFilialEmpresa As Integer
    lNumBordero As Long
    dtDataBackoffice As Date
    dtDataEnvio As Date
    dtDataImpressao As Date
    dValor As Double
    dValorN As Double
    lNumIntDocCPR As Long
    sAdmMeioPagto As String
    sNomeParcelamento As String
    lNumMovtoCx As Long
End Type

Type typeCaixa
    iCodigo As Integer
    iFilialEmpresa As Integer
    sNomeReduzido As String
    sDescricao As String
    iStatus As Integer
    iTeclado As Integer
    dtDataInicial As Date
    lProxSeqMov As Long
    iPos As Integer
    iTEF As Integer
    iBoletoManual As Integer
    iAtivo As Integer
    dtDataLog As Date
    iOrcamentoECF As Integer
    iUltimoOperador As Integer
    iSessaoStatus As Integer
End Type

Type typeCCMov
    iCodCaixa As Integer
    iFilialEmpresa As Integer
    iAno As Integer
    iTipoMeioPagto As Integer
    iAdmMeioPagto As Integer
    iParcelamento As Integer
    dSaldoInicial As Double
    dDeb01 As Double
    dCred01 As Double
    dDeb02 As Double
    dCred02 As Double
    dDeb03 As Double
    dCred03 As Double
    dDeb04 As Double
    dCred04 As Double
    dDeb05 As Double
    dCred05 As Double
    dDeb06 As Double
    dCred06 As Double
    dDeb07 As Double
    dCred07 As Double
    dDeb08 As Double
    dCred08 As Double
    dDeb09 As Double
    dCred09 As Double
    dDeb10 As Double
    dCred10 As Double
    dDeb11 As Double
    dCred11 As Double
    dDeb12 As Double
    dCred12 As Double
End Type

Type typeCCMovDia
    iCodCaixa As Integer
    dtData As Date
    iTipoMeioPagto As Integer
    iCondPagto As Integer
    dDeb As Double
    dCred As Double
End Type

'Type typeCheque
'    lNumIntCheque As Long
'    iTipo As Integer
'    iFilialEmpresa As Integer
'    iECF As Integer
'    iOperador As Integer
'    dtDataRecebimento As Date
'    dtDataDeposito As Date
'    lCliente As Long
'    iFilial As Integer
'    sCGC As String
'    iBanco As Integer
'    sAgencia As String
'    sAgenciaDV As String
'    sContaCorrente As String
'    sContaCorrenteDV As String
'    sNumero As String
'    sNumeroDV As String
'    dValor As Double
'    sCMC7 As String
'    lBordero As Long
'    iGarantido As Integer
'    iAprovado As Integer
'End Type

Type typeCondPagtoLoja
    iIntervalosVariaveis As Integer
End Type

Type typeCupomFiscal
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    iECF As Integer
    iStatus As Integer
    dtDataEmissao As Date
    lNumero As Long
    lCliente As Long
    iFilialCli As Integer
    lNumOrcamento As Long
    dValorTotal As Double
    dValorProdutos As Double
    dValorDesconto As Double
    dValorAcrescimo As Double
    sMensagem As String
    iTabelaPreco As Integer
    sNaturezaOp As String
    lVolumeQuant As Long
    sObservacao As String
    sCodUsuarioCancel As String
    sMotivoCancel As String
    sCPFCGC As String
    dHoraEmissao As Double
    lGerenteCancel As Long
    iVendedor As Integer
    iCaixa As Integer
    
End Type

Type typeECF
    
    iCodigo As Integer
    iFilialEmpresa As Integer
    iCaixa As Integer
    iImpressoraECF As Integer
    iImpressoraCheque As Integer
    iHorarioVerao As Integer
    iAtivo As Integer
    dtDataLog As Date
    
End Type

Type TypeImpressoras
    iCodigo As Integer
    sNome As String

End Type

Type typeFabricanteECF
    iCodigo As Integer
    sNome As String
End Type

Type typeFechamentoBoletos
    lNumIntDoc As Long
    iNumIntDoc As Integer
    sNumIntDoc As String
    sLote As String
    dtLote As Date
End Type

Type typeGerente
    iFilialEmpresa As Integer
    iCodigo As Integer
    sCodUsuario As String
End Type

Type typeItemCupomFiscal
    lNumIntDoc As Long
    lNumIntCupom As Long
    iNumIntCupom As Integer
    iStatus As Integer
    sProduto As String
    sUnidadeMed As String
    dQuantidade As Double
    dPrecoUnitario As Double
    dPercDesc As Double
    dValorDesconto As Double
    dAliquotaICMS As Double
    sSituacaoTrib As String
End Type

Type typeKitVenda
    sProdutoRaiz As String
    sVersao As String
    dtData As Date
    sObservacao As String
End Type

Type typeLoja
    iImprimeItemAItem As Integer
    sNatOpPadrao As String
    sMensagemCupom As String
    iOperadorIgualVendedor As Integer
    iTabelaPreco As Integer
    iTelaVendaMP As Integer
    iAtualizacaoECF As Integer
    sSimboloMoeda As String
    iCupomDescreveFormaPagto As Integer
    lEspacoEntreLinhas As Long
    iLinhasEntreCupons As Integer
    sNumLimRO As String
    sTruncamentoArredondamento As String
End Type

Type typeLojaConfig
    sCodigo As String
    iFilialEmpresa As Integer
    sDescricao As String
    iTipo As Integer
    sConteudo As String
End Type

Type typeMovimentoCaixa
    iFilialEmpresa As Integer
    lNumMovto As Long
    iCodConta As Integer
    iCodOperador As Integer
    iCaixa As Integer
    lSequencial As Long
    iTipo As Integer
    iAdmMeioPagto As Integer
    iParcelamento As Integer
    iTipoCartao As Integer
    lNumero As Long
    dtDataMovimento As Date
    dValor As Double
    sHistorico As String
    sFavorecido As String
    lCupomFiscal As Long
    lNumRefInterna As Long
    lMovtoTransf As Long
    lMovtoEstorno As Long
    iGerente As Integer
    dHora As Double
    lNumIntDocLog As Long
    iQuantLog As Integer
    lNumIntExt As Long
End Type

Type typeOperador
    
    iFilialEmpresa As Integer
    iCodigo As Integer
    sNome As String
    sSenha As String
    iDesconto As Integer
    iLimiteDesconto As Integer
    iCodigoVendedor As Integer
    iGerente As Integer
    iAtivo As Integer
    dtDataLog As Date
    
End Type


Type typePOS
    sCodigo As String
    iFilialEmpresa As Integer
    iRede As Integer
End Type

Type typeRede
    iCodigo As Integer
    iFilialEmpresa As Integer
    sNome As String
    iTEF As Integer
    lCliente As Long
    iFilialCli As Integer
    lClienteLoja As Long
    iFilialCliLoja As Integer
    iAtivo As Integer
    dtDataLog As Date
    iBandeira As Integer
    sEstabelecimento As String
    iCodConta As Integer
    sDirImportacaoExtrato As String
End Type

Type typeReducaoZ
    dtDataHora As Date
    iNumeroECF As Integer
    sRazaoSocial As String
    sCNPJ As String
    sInscEstadual As String
    lNumOperacao As Long
    lReducao As Long
    dTotalAcumulado As Double
    dCancelamento As Double
    dDesconto As Double
    dVendaBrutalDia As Double
    dVendaLiquidaDia As Double
    dVendaSubstTributaria As Double
    dVendasIsentas As Double
    dVendasNaoTributadas As Double
    dVendasTributadas As Double
End Type

Type typeSessao
    lNumInt As Long
    iCaixa As Integer
    dtDataInicio As Date
    iAbertura As Integer
    dtDataFim As Date
    iFilialEmpresa As Integer
    iOperador As Integer
    lGerenteAbertura As Long
    lGerenteFechamento As Long
    iStatus As Integer
    iFechamento As Integer
End Type


Type typeTecladoProdutoItens
    iTeclado As Integer
    sProduto As String
    sTitulo As String
    lCor As Long
    iTecla As Integer
    iIndice As Integer
    sArvoreKey As String
End Type

Type typeTecladoProduto
    iTeclado As Integer
    iCodigo As Integer
    iFilialEmpresa As Integer
    sDescricao As String
    iPadrao As Integer
End Type

Type typeTipoMeioPagtoLoja
    
    iTipo As Integer
    iInativo As Integer
    sDescricao As String
    iExigeNumero As Integer
    iEnvioPagamento As Integer
    iPossuiAdm As Integer
    dSaldo As Double
    iTransferencia As Integer
    iExigeRede As Integer
    
End Type

Type typeTipoMovtoCaixa
    iCodigo As Integer
    sDescricao As String
    sNomeReduzido As String
    sSigla As String
    sSignificadoRefInterna As String
    iCredito As Integer
    iPodeCaixaECF As Integer
    iPodeCaixaCentral As Integer
    iPodeCaixaGeral As Integer
    iRelMovCaixa As Integer
    iTipoMeioPagto As Integer
End Type

Type typeValeTicket
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    iECF As Integer
    iOperador As Integer
    sAdmMeioPagto As String
    dtDataRecebimento As Date
    dValor As Double
    dValorRecebido As Double
    lBordero As Long
    iStatus As Integer
End Type

Type typeProdutoKitVenda
    sProdutoRaiz As String
    sVersao As String
    iSeq As Integer
    sProduto As String
    dQuantidade As Double
    sUnidadeMed As String
End Type


Type typeAdmMeioPagtoCondPagto
    
    iAdmMeioPagto  As Integer
    iFilialEmpresa As Integer
    iParcelamento As Integer
    sNomeParcelamento As String
    iNumParcelas As Integer
    iParcelasRecebto As Integer
    dTaxa As Double
    dValorMinimo As Double
    dDesconto As Double
    iJurosParcelamento As Integer
    dJuros As Double
    dSaldo As Double
    iAtivo As Integer
    dtDataLog As Date
    iPreDatado As Integer
    
End Type


Type typeAdmMeioPagtoParcelas
    
    iAdmMeioPagto As Integer
    iFilialEmpresa As Integer
    iParcelamento As Integer
    iParcela As Integer
    dPercRecebimento As Double
    iIntervaloRecebto As Long
    lTotalEspecificados As Long
    
End Type
    
'Type para tela de CancelaRecebimentoCarneVar

Type TypeInfoRecebimentoCarneVar
    
    vlCodCliente As Variant
    vsCodCarneDe As Variant
    vsCodCarneAte As Variant
    vdtCodDataVenctoAte As Variant
    vdtCodDataVenctoDe As Variant
    vsCarneNumero As Variant
    viParcelaNumero As Variant
    vlParcelaNumIntDoc As Variant
    vdtParcelaVencimento As Variant
    vdParcelaValor As Variant
    vdParcelaDesconto As Variant
    vdParcelaMulta As Variant
    vdParcelaJuros As Variant
    viStatus As Variant
    viFilialEmpresa As Variant
    vlNumIntDoc As Variant
    
End Type

'Type para carneParcelasImpressao

Type TypeCarneParcelasImpressao
    
    lCodCliente As Long
    sCodCarne As String
    iCarneNumero As Integer
    dtParcelaVencimento As Date
    dValor As Double
    dValorBaixado As Double
    dDesconto As Double
    dMulta As Double
    dJuros As Double
    
End Type


'Type referênte a Tela de OpRelProdutosRanking

Type TypeProdutosRankingVar

    vdtDataDe As Variant
    vdtDataAte As Variant
    viClassificacao As Variant
    vsProdutoDe As Variant
    vsProdutoAte As Variant
    viTipoProdutoDe As Variant
    viTipoProdutoAte As Variant
    vsCategoria As Variant
    viNumIntRel As Variant
    vlRanking As Variant
    vsProduto As Variant
    vsNomeReduzido As Variant
    vsItemCategoria As Variant
    vdQuantidade As Variant
    vdValor As Variant
    viFilialEmpresa As Variant

End Type


'Type que vai ser usado no Relatórios de Flash de vendas
Type TypeRelFlashVendasVar

    vsProduto As Variant
    vsUMVenda As Variant
    viFilialEmpresa As Variant
    vdtData As Variant
    vdHoraIni As Variant
    vdHoraFim As Variant
    viCaixaIni As Variant
    viCaixaFim As Variant
    vlNumVendas As Variant
    vdQuantVendas As Variant
    vdValorVendido As Variant
    vsUMMedida As Variant
    
End Type

'Type Relacionada a Tela de Relatório RelOpFatProduto
'Inserido por Sergio dia 24/01/03
Type typeSldDiaFatCxDimVar

    vsProdutoDe As Variant
    vsProdutoAte As Variant
    viFilialEmpresa As Variant
    vdtDataDe As Variant
    vdtDataAte As Variant
    viTipoProdutoDe As Variant
    viTipoProdutoAte As Variant
    viCaixaDe As Variant
    viCaixaAte As Variant
    viCaixa As Variant
    vdtData As Variant
    vsProduto As Variant
    vdValorFaturado As Variant
    vdQuantFaturada As Variant
    vlNumVendas As Variant
    
End Type

Type typeImpressoraECF
    iFilialEmpresa As Integer
    iCodigo As Integer
    iCodModelo As Integer
    sNumSerie As String
End Type

Type typeModeloECF
    iCodigo As Integer
    sNome As String
    sFabricante As String
End Type

Type typeTransfCaixa
    iFilialEmpresa As Integer
    lCodigo As Long
    dtDataBackoffice As Date
    lNumMovtoCxDe As Long
    lNumMovtoCxPara As Long
End Type

Type typeArqSeq
    sSequencial As String * 10
    sData As String * 10
End Type

Type typeComissoesCF
    iFilialEmpresa As Integer
    lNumIntDoc As Long
    iCodVendedor As Integer
    dValorBase As Double
    dValorComissao As Double
    iIndireta As Integer
End Type

Type typeLojaArqFisMestre
    iCodECF As Integer
    iFilialEmpresa As Integer
    dtData As Date
    sNumSerieECF As String
    lCOOIni As Long
    lCOOFim As Long
    lCRZ As Long
    dGrandeTotal As Double
    lCRO As Long
    dVendaBruta As Double
    iNumEquip As Integer
End Type


Type typeLojaReducao
    iCodECF As Integer
    iFilialEmpresa As Integer
    dtData As Date
    dAcrescimoICMS As Double
    dAcrescimoISS As Double
    dAcrescimoNaoFiscal As Double
    dCancelamentoICMS As Double
    dCancelamentoISS As Double
    dCancelamentoNaoFiscal As Double
    dDescontoICMS As Double
    dDescontoISS As Double
    dDescontoNaoFiscal As Double
    dIsentoICMS As Double
    dIsentoISS As Double
    dNaoIncideICMS As Double
    dNaoIncideISS As Double
    dSubstTribICMS As Double
    dSubstTribISS As Double
    dTotalNaoFiscal As Double
    dVendaBruta As Double
    sIndiceDescontoISS As String
    dHoraReducao As Double
End Type

Type typeLojaReducaoAliquota
    iCodECF As Integer
    iFilialEmpresa As Integer
    dtData As Date
    dAliquota As Double
    iISS As Integer
    dTotalizador As Double
End Type


Type typeD1

    dtDataDAV As Date
    sCNPJ As String
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    sInscEstadual As String
    sInscMunicipal As String
    sRazaoSocial As String
    lTotRegD2 As Long
    lTotRegD3 As Long
    lTotRegD4 As Long
    sEAD As String
End Type


Type typeD2

    sCNPJ As String
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    lCOO As Long
    sNumeroDAV As String
    dtDataDAV As Date
    sTituloDAV As String
    dValorDAV As Double
    lCOOCupomVinculado As Long
    iSequencialECFVinculado As Integer
    sNomeCliente As String
    sCNPJCliente As String
    sEAD As String
    lCodOrcamento As Long
    
End Type


Type typeD3

    sCNPJ As String
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    lCOO As Long
    sNumeroDAV As String
    iItemDAV As Integer
    dtDataDAV As Date
    sCodProduto As String
    sDescProduto As String
    dQuantidade As Double
    sUM As String
    dValorUnitario As Double
    dDesconto As Double
    dAcrescimo As Double
    dValorTotal As Double
    dAliquota As Double
    sSituacaoTributaria As String
    sEAD As String
    lCodOrcamento As Long
    sIndicadorCancelamento As String
    
End Type

Type typeD4

    sCNPJ As String
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    lCOO As Long
    sNumeroDAV As String
    iItemDAV As Integer
    dtDataAlteracao As Date
    dHoraAlteracao As Double
    sCodProduto As String
    sDescProduto As String
    dQuantidade As Double
    sUM As String
    dValorUnitario As Double
    dDesconto As Double
    dAcrescimo As Double
    dValorTotal As Double
    dAliquota As Double
    sSituacaoTributaria As String
    sEAD As String
    lCodOrcamento As Long
    sIndicadorCancelamento As String
    sTipoAlteracao As String
    
End Type


Type typeE1

    dtDataEstoque As Date
    dHoraEstoque As Double
    sCNPJ As String
    sInscEstadual As String
    sInscMunicipal As String
    sRazaoSocial As String
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    lTotRegE2 As Long
    
End Type

Type typeE2

    sCodProduto As String
    sDescricao As String
    sUM As String
    sPositivoNegativo As String
    lQuantidade As Long
    sCNPJ As String
    sEAD As String
    
End Type

Type typeE3

    dtDataEstoque As Date
    dHoraEstoque As Double
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    sEAD As String
    lTotRegE2 As Long
    
End Type


Type typeP1

    sCNPJ As String
    sInscEstadual As String
    sInscMunicipal As String
    sRazaoSocial As String
    lTotRegP2 As Long
    
End Type

Type typeP2

    sCNPJ As String
    sCodProduto As String
    sDescricao As String
    sUM As String
    sIAT As String
    sIPPT As String
    sSituacaoTributaria As String
    dAliquota As Double
    dValorUnitario As Double
    sEAD As String
    
End Type


Type typeR01

    dtData As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    sVersaoSB As String
    dtDataInstalacaoSB As Date
    sHoraInstalacaoSB As String
    iSequencialECF As Integer
    sCNPJUsu As String
    sIEUsu As String
    sCNPJDesenv As String
    sIEDesenv As String
    sIMDesenv As String
    sNomeDesenv As String
    sNomePAFECF As String
    sVersaoPAFECF As String
    sMD5PAFECF As String
    sVersaoEspecPAFECF As String
    sCodNacId As String
    sEAD As String
    lTotRegR02 As Long
    lTotRegR03 As Long
    lTotRegR04 As Long
    lTotRegR05 As Long
    lTotRegR06 As Long
    lTotRegR07 As Long
    
End Type
    

Type typeR02

    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCRZ As Long
    lCOO As Long
    lCRO As Long
    dtDataEmissaoRedZ As Date
    sHoraEmissaoRedZ As String
    dVendaBruta As Double
    sIncidenciaDescontoISS As String
    sEAD As String
    
End Type

Type typeR03

    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCRZ As Long
    sTotalizadorParcial As String
    dValor As Double
    sEAD As String
    
End Type

Type typeR04
    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCCF As Long
    lCOO As Long
    dtDataEmissao As Date
    dSubtotal As Double
    dDesconto As Double
    sTipoDesconto As String
    dAcrescimo As Double
    sTipoAcrescimo As String
    dValorTotal As Double
    sIndicadorCancelamento As String
    dValorCancAcrescimo As Double
    sOrdemDescAcresc As String
    sNomeAdiquirente As String
    sCPFCNPJ As String
    sEAD As String
End Type

Type typeR05
    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCOO As Long
    lCCF As Long
    iItem As Integer
    sCodProduto As String
    sDescProduto As String
    dQuantidade As Double
    dValorUnitario As Double
    dDesconto As Double
    dAcrescimo As Double
    dValorTotal As Double
    sTotalizadorParcial As String
    sIndicadorCancelamento As String
    dQuantidadeCancelada As Double
    dValorCancelado As Double
    dValorCancelAcrescimo As Double
    sIAT As String
    sPPT As String
    iCasasdecimaisqtde As Integer
    iCasasdecimaisvalor As Integer
    sUM As String
    sEAD As String
    
End Type

Type typeR06
    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCOO As Long
    lGNF As Long
    lGRG As Long
    lCDC As Long
    sDenominacao As String
    dtDataFinalEmissao As Date
    sHoraFinalEmissao As String
    sEAD As String
    
End Type


Type typeR07

    dtDataMovimento As Date
    sNumeroSerie As String
    sMFAdicional As String
    sTipoECF As String
    sMarcaECF As String
    sModeloECF As String
    iNumeroUsuario As Integer
    lCOO As Long
    lGNF As Long
    lCCF As Long
    sMeioPagamento As String
    dValor As Double
    sIndicadorEstorno As String
    dValorEstorno As Double
    sEAD As String
    
End Type


Type typeMeioPagamento

    dtDataMovimento As Date
    iCodTipoDocumento As Integer
    sMeioPagamento As String
    dValor As Double
    sEAD As String

End Type

Public Const STRING_NFCE_TOKEN = 6 'em desuso
Public Const STRING_PORTA_IMPRESSORA = 20

Type typeConfiguracaoNFe
    sToken As String
    sNFCeSerie As String
    lNFCeProximoNum As Long
    lNFCeProximoLote As Long
    sDirArqXml As String
    sCertificadoA1A3 As String
    iNFeAmbiente As Integer
    sNFeSerie As String
    lNFeProximoNum As Long
    lNFeProximoLote As Long
    sDirXsd As String
    iNFCeAmbiente As Integer
    sNFCECSC As String
    sidNFCECSC As String
    iEmContingencia As Integer
    dtContingenciaDataEntrada As Date
    dContingenciaHoraEntrada As Double
    sContigenciaxJust As String
    iModeloImpressora As Integer
    sPortaImpressora As String
    sSMTP As String
    sSMTPUsu As String
    sSMTPSenha As String
     lSMTPPorta As Long
    iNFCeImprimir As Integer
    iNFCeEnviarEmail As Integer
    iNFDescricaoProd As Integer
    iVersaoNFe As Integer
    iFocaTipoVenda As Integer
End Type

Public Const STRING_SAT_CODIGO_ATIVACAO = 32
Public Const STRING_SAT_SIGNAC = 344

Type typeConfiguracaoSAT
    sCodigoDeAtivacao As String
    iEmuladorSefaz As Integer
    sDirArqXml As String
    sNomeArqDLL As String
    sNomeArqEmulador As String
    iModeloImpressora As Integer
    iLayoutImpressao As Integer
    iEmTeste As Integer
    sNomeArqLogo As String
    sPortaImpressora As String
    ssignAC As String
End Type

Type typeConfiguracaoECF

    sCNPJDesenv As String
    sIEDesenv As String
    sIMDesenv As String
    sRazaoSocialDesenv As String
    sNomePAFECF As String
    sVersaoPAFECF As String
    sEndDesenv As String
    sTelDesenv As String
    sContatoDesenv As String
    sNumLaudo As String
    sVersaoEspReqPAFECF As String
    sPrincExec As String
    sDirPAFECF As String

End Type

Type typeOrcamentoECF
    lCodigo As Long
    iSeq As Integer
    sClienteNomeRed As String
    sCPFCNPJ As String
    sMsg As String
    iStatus As Integer
    dtDataEmissao As Date
    sNumeroDAV As String
    lCOO As Long
    lCOOCupom As Long
    iDAVImpresso As Integer
    sEAD As String
End Type

