Attribute VB_Name = "GlobalArtmill"
Option Explicit

Public Const ARTMILL_STRING_PRODUTO_CODANTERIOR = 30
Public Const ARTMILL_STRING_DETALHE_COR = 20
Public Const ARTMILL_STRING_DIM_EMBALAGEM = 50
Public Const PAGAMENTO_ANTECIPADO = "Pagamento Antecipado"
Public Const BLOQUEIO_PAGTO_ANTECIPADO = 7
Public Const ARTMILL_CATCLIENTE_TROCA_FILIAL_FAT = "TROCA FILIAL FAT"
Public Const ARTMILL_CATCLIENTE_ITEM_SIM = "SIM"
Public Const ARTMILL_CATCLIENTE_ITEM_NAO = "NAO"
Public Const ARTMILL_CATCLIENTE_ITEM_NÃO = "NÃO"
Public Const DELTA_FILIALREAL_OFICIAL1 = 50
