Attribute VB_Name = "GLOBALCONTAB"
Option Explicit

Type typeMnemonicoFPTipo
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    iEscopo As Integer
    sItemCategoria As String
    sProduto As String
    iTabelaPreco As Integer
    sMnemonico As String
    iTipo As Integer
    iNumParam As Integer
    iParam1 As Integer
    iParam2 As Integer
    iParam3 As Integer
    sMnemonicoDesc As String
    sExpressao As String
    iFuncao As Integer
    iTipoPlanilha As Integer
End Type

Public Const SPED_CONTAB_TIPO_NORMAL = 0
Public Const SPED_CONTAB_TIPO_FCONT = 1

Public Const FCONT_IND_PER_INI_ANO = 0
Public Const FCONT_IND_PER_ABERTURA = 1
Public Const FCONT_IND_PER_CISAO_FUSAO = 2
Public Const FCONT_IND_PER_INI_OBR = 3

'constante usada na tela Planilhas
Public Const PLANILHA_TIPO_TODOS = 1
Public Const PLANILHA_TIPO_DVV = 2
Public Const PLANILHA_TIPO_IMPORTACAO = 3
Public Const STRING_TIPOPLANILHA_DESCRICAO = 50

Public Const EXIGE_CONTABILIZACAO = 1
Public Const NAO_EXIGE_CONTABILIZACAO = 0

Public Const STRING_SERIE = 11 'serie de nota fiscal (aumentado de 5 para 9 em 16/12/2014 para suportar serie de SAT CFe)

'Indica se é pedido de venda ou nota fiscal
Public Const NOTA_FISCAL = 0
Public Const PEDIDO_DE_VENDA = 1
Public Const PEDIDO_DE_VENDA_GRADE = 2
Public Const CUPOM_FISCAL = 3

'Nome de fórmulas que podem ser usadas pela máquina de expressões
Public Const FORMULA_FUNCAO_NUMTEXTO As String = "NUM_TEXTO"
Public Const FORMULA_FUNCAO_IF As String = "IF"
'*****************************************************************

Public Const EXCLUI_LANCAMENTOS_CONTABEIS = 0
Public Const NAO_EXCLUI_LANCAMENTOS_CONTABEIS = 1 'Utilizado pela rotina de interface com a folha de pagamento para permitir incluir vários lançamentos num só documento, com um minimo de alteracao do codigo existente

Public Const FLUXOCAIXA_UTILIZADO = 1
Public Const FLUXOCAIXA_NAO_UTILIZADO = 0

Public Const TRANSACAOCTB_BAIXAPAG = 27

Public Const TRANSACAOCTBORIGEM_APLICACOES = 1
Public Const TRANSACAOCTBORIGEM_BAIXASPAG = 2
Public Const TRANSACAOCTBORIGEM_BAIXASPARCPAG = 3
Public Const TRANSACAOCTBORIGEM_BAIXASPARCREC = 4
Public Const TRANSACAOCTBORIGEM_BAIXASREC = 5
Public Const TRANSACAOCTBORIGEM_CREDITOSPAGFORN = 6
Public Const TRANSACAOCTBORIGEM_DEBITOSRECCLI = 7
Public Const TRANSACAOCTBORIGEM_MOVIMENTOESTOQUE = 8
Public Const TRANSACAOCTBORIGEM_MOVIMENTOSCONTACORRENTE = 9
Public Const TRANSACAOCTBORIGEM_NFISCAL = 10
Public Const TRANSACAOCTBORIGEM_NFSPAG = 11
Public Const TRANSACAOCTBORIGEM_OCORRENCIASPARCREC = 12
Public Const TRANSACAOCTBORIGEM_PAGTOSANTECIPADOS = 13
Public Const TRANSACAOCTBORIGEM_RECEBANTECIPADOS = 14
Public Const TRANSACAOCTBORIGEM_TITULOSPAG = 15
Public Const TRANSACAOCTBORIGEM_TITULOSREC = 16
Public Const TRANSACAOCTBORIGEM_TRANSFCARTCOBR = 17


Public Const CONTABIL_EXCLUI_SEM_ESTORNO = 1 'não estorna os lançamentos já atualizados
Public Const CONTABIL_EXCLUI_ESTORNO_DOC_ZERADO = 2 'Só estorna os lançamentos atualizados se o número do documento da tela estiver zerado. Isto foi feito para evitar ficar gerando estornos desnecessariamente.
Public Const CONTABIL_EXCLUI_EFETIVO = 3 'Exclui a contabilização mesmo que esteja atualizada

Public Const VOUCHER_NORMAL = 0
Public Const VOUCHER_ESTORNADO = 1
Public Const VOUCHER_ESTORNADOR = 2
Public Const VOUCHER_EXCLUSAO = 3

Public Const STRINT_VOUCHER_NORMAL = "Normal"
Public Const STRINT_VOUCHER_ESTORNADO = "Estornado"
Public Const STRINT_VOUCHER_ESTORNADOR = "Estornador"


Public Const ESCANINHO_CUSTO = "Escaninho_Custo"
Public Const ESCANINHO_CUSTO_CONSIG = "EscaninhoCustoConsig"
Public Const QUANT_ALOCADA_CONSIG = "Quant_Alocada_Consig"
Public Const QUANT_BENEFICIADA = "Quant_Beneficiada"
Public Const ESCANINHO_CUSTO_BENEF = "EscaninhoCustoBenef"

'TransacaoCTBOrigem - Codigos
Public Const ORIGEM_LCTO_NFISCAL = 10
Public Const ORIGEM_LCTO_MOVESTOQUE = 8

Public Const ESCANINHO_NOSSO = 0
Public Const ESCANINHO_NOSSO_EM_CONSIGNACAO = 1
Public Const ESCANINHO_NOSSO_EM_CONSERTO = 2
Public Const ESCANINHO_NOSSO_EM_DEMO = 3
Public Const ESCANINHO_NOSSO_EM_OUTROS = 4
Public Const ESCANINHO_NOSSO_EM_BENEF = 5
Public Const ESCANINHO_3_EM_CONSIGNACAO = 6
Public Const ESCANINHO_3_EM_CONSERTO = 7
Public Const ESCANINHO_3_EM_DEMO = 8
Public Const ESCANINHO_3_EM_OUTROS = 9
Public Const ESCANINHO_3_EM_BENEF = 10
Public Const ESCANINHO_DEFEITUOSO = 11
Public Const ESCANINHO_INDISPONIVEL = 12
Public Const ESCANINHO_RECEBIDO_INDISPONIVEL = 13

Public Const REJEITA_RECEBIMENTO = 0
Public Const ACEITA_RECEBIMENTO = 1

Public Const NAO_AVISA_E_ACEITA_RECEBIMENTO = 0
Public Const ERRO_E_REJEITA_RECEBIMENTO = 1
Public Const AVISA_E_ACEITA_RECEBIMENTO = 2

'Recebimento fora da faixa
Public Const MENSAGEM_REJEITA_RECEBIMENTO = "Rejeita Recebimento"
Public Const MENSAGEM_ACEITA_RECEBIMENTO = "Avisa e Aceita Recebimento"
Public Const MENSAGEM_NAO_AVISA_ACEITA_RECEBIMENTO = "Não Avisa e Aceita Recebimento"

Public Const NAO_AVALIA_PELO_CUSTO_REAL_PRODUCAO = -1
Public Const AVISA_LANCAMENTOS_CONTABILIZADOS = 1
Public Const NAO_AVISA_LANCAMENTOS_CONTABILIZADOS = 0
Public Const NUMERO_NOTA_FISCAL As String = "{NF}"
Public Const HIST_CTB_NUMERO_FAT As String = "{FT}"

'Custo de Produção Apurado
Public Const CUSTO_APURADO = 1
Public Const CUSTO_NAO_APURADO = 0

Public Const STRING_CUSTO_APURADO = "Apurado"
Public Const STRING_CUSTO_NAO_APURADO = "Não Apurado"

'Constantes referentes as tabelas RelDRE e RelDMPL
Public Const RELDRE As String = "DRE"
Public Const RELDMPL As String = "DMPL"
Public Const RELDOAR As String = "DOAR"
Public Const CONTAS_EXERCICIO_ATUAL = 0
Public Const CONTAS_EXERCICIO_ANTERIOR = 1

'Tipos de Elementos do Relatorio Demonstração do Resultado do Exercicio (DRE)
Public Const DRE_TIPO_TITULO = 2
Public Const DRE_TIPO_GRUPOCONTA = 0
Public Const DRE_TIPO_CONTA = 0
Public Const DRE_TIPO_FORMULA = 1
Public Const DRE_OPERACAO_SOMA = 0
Public Const DRE_OPERACAO_SUBTRAI = 1

Public Const STRING_MNEMONICOCTB_VALOR = 50
Public Const STRING_MNEMONICOCTB_DESCRICAO = 50

Public Const STRING_MNEMONICOFPRECO_MNEMONICO = 20
Public Const STRING_MNEMONICOFPRECO_MNEMONICODESC = 255
Public Const STRING_MNEMONICOFPRECO_EXPRESSAO = 255

Public Const GRUPOTRANSEXC_BAIXAPARCPAG = 1
Public Const GRUPOTRANSEXC_BAIXAPARCREC = 2
Public Const GRUPOTRANSEXC_OCORRREMPARCREC = 3
Public Const GRUPOTRANSEXC_BAIXAPAG = 4
Public Const GRUPOTRANSEXC_BAIXAREC = 5

'Unidade de Medida
Public Const UM_EDITAVEL = 1
Public Const UM_NAO_EDITAVEL = 0

Public Const NAO_INCLUI_SALDO_INICIAL = 0
Public Const INCLUI_SALDO_INICIAL = 1
Public Const CTB_RATEIOON_TESTA_EXISTENCIA = 1
Public Const CTB_RATEIOON_NAO_TESTA_EXISTENCIA = 0

'??? sera substituida por STRING_UM_SIGLA
Public Const STRING_UM_SIGLA_UM_BASE = 5

'Indica se um elemento do Relatorio DRE será impresso
Public Const DRE_NAO_IMPRIME = 0
Public Const DRE_IMPRIME = 1

'Campo Tipo
Public Const DOCINFO_PEDIDO_VENDA = 0
Public Const DOCINFO_NF_INT_ENTRADA = 1
Public Const DOCINFO_NF_INT_SAIDA = 2
Public Const DOCINFO_NF_EXTERNA = 3
Public Const DOCINFO_RECEB_FORN = 4
Public Const DOCINFO_RECEB_CLI = 5

Public Const NUM_MAX_ITENS_FORMULAS_DRE = 100
Public Const NUM_MAX_ITENS_CONTAS_DRE = 100
Public Const SEM_TITULO = "Sem Título"

'Tipos de Rateio Offline
Public Const TIPO_RATEIOOFF_MENSAL = 1
Public Const TIPO_RATEIOOFF_ACUMULADO = 0

Public Const NUM_MAX_ITENS_CONTAS_RATEIOOFF = 20

'Caso o mnemonico não tenha sido tratado na tela
Public Const CONTABIL_MNEMONICO_NAO_ENCONTRADO = 1

'Caso o mnemônico não tenha sido encontrado
Public Const MNEMONICOCOMISSOES_NAO_ENCONTRADO = 1

'Tipos de apropriação de custo - Tabela Produtos e Tabela MovimentoEstoque
Public Const APROPR_CUSTO_MEDIO = 0
Public Const APROPR_CUSTO_STANDARD = 1
Public Const APROPR_CUSTO_INFORMADO = 2
Public Const APROPR_CUSTO_REAL = 3  'Custo real de produção
Public Const APROPR_CUSTO_MEDIO_PRODUCAO = 4  'Custo médio real de produção

'Indicacao se apropria pelo custo real de produção ou não - Tabela LanPendente
Public Const LANPENDENTE_APROPR_CRPROD = 1
Public Const LANPENDENTE_NAO_APROPR_CRPROD = 0

Public Const RATEIO_MENSAL = 1
Public Const RATEIO_ACUMULADO = 0

'
'chaves em FATConfig
Public Const FATCFG_AGLUTINA_LANCAM_POR_DIA = "AGLUTINA_LANCAM_POR_DIA"
Public Const FATCFG_FILIAL_FATURAMENTO = "FILIAL_FATURAMENTO"
Public Const FATCFG_GERA_LOTE_AUTOMATICO = "GERA_LOTE_AUTOMATICO"
Public Const FATCFG_NFISCAL_ALOCA_AUTOMATICA = "NFISCAL_ALOCA_AUTOMATICA"
Public Const FATCFG_NFISCAL_EDITA_COMISSAO = "NFISCAL_EDITA_COMISSAO"
Public Const FATCFG_NUM_PROX_CANAL_VENDA = "NUM_PROX_CANAL_VENDA"
Public Const FATCFG_NUM_PROX_CODIGO_PEDVENDA = "NUM_PROX_CODIGO_PEDVENDA"
Public Const FATCFG_NUM_PROX_ITEM_PEDVENDA = "NUM_PROX_ITEM_PEDVENDA"
Public Const FATCFG_NUM_PROX_PEDIDO_VENDA = "NUM_PROX_PEDIDO_VENDA"
Public Const FATCFG_NUM_PROX_RELPRAZOPAGTO = "NUM_PROX_RELPRAZOPAGTO"
Public Const FATCFG_NUM_PROX_TIPO_DE_BLOQUEIO = "NUM_PROX_TIPO_DE_BLOQUEIO"
Public Const FATCFG_PEDIDO_RESERVA_AUTOMATICA = "PEDIDO_RESERVA_AUTOMATICA"
Public Const FATCFG_PEDIDO_VENDA_EDITA_COMISSAO = "PEDIDO_VENDA_EDITA_COMISSAO"
Public Const FATCFG_SERIE_PADRAO = "SERIE_PADRAO"
Public Const FATCFG_FORMATO_PRECO_UNITARIO = "FORMATO_PRECO_UNITARIO"
Public Const FATCFG_CATEG_CUSTO_FIXO = "CATEG_CUSTO_FIXO"
Public Const FATCFG_CATEG_MOEDA = "CATEG_MOEDA"
Public Const FATCFG_PVPREENCH_CONDPAGTO = "PVPREENCH_CONDPAGTO"
Public Const FATCFG_CLIPREENCH_CONDPAGTO = "CLIPREENCH_CONDPAGTO"
Public Const FATCFG_CLIPREENCH_TRANSP = "CLIPREENCH_TRANSP"
Public Const FATCFG_CLIPREENCH_CNPJ = "CLIPREENCH_CNPJ"
Public Const FATCFG_CLIPREENCH_INSCEST = "CLIPREENCH_INSCEST"
Public Const FATCFG_PEDIDO_VALIDA_EMBALAGEM = "PEDIDO_VALIDA_EMBALAGEM"
Public Const FATCFG_PEDVENDA_CODBARRA = "FATCFG_PEDVENDA_CODBARRA"
Public Const FATCFG_BLOQUEIA_EDICAO_PRECO_PV = "BLOQUEIA_EDICAO_PRECO_PV"

Public Const FATCFG_CLIPREENCH_VEND = "CLIPREENCH_VEND"
Public Const FATCFG_CLIPREENCH_DTULTVI = "CLIPREENCH_DTULTVI"
Public Const FATCFG_CLIPREENCH_END = "CLIPREENCH_END"
Public Const FATCFG_CLIPREENCH_ENDNUM = "CLIPREENCH_ENDNUM"
Public Const FATCFG_CLIPREENCH_ENDCOMPL = "CLIPREENCH_ENDCOMPL"
Public Const FATCFG_CLIPREENCH_CEP = "CLIPREENCH_CEP"
Public Const FATCFG_CLIPREENCH_TELEFONE = "CLIPREENCH_TELEFONE"
Public Const FATCFG_CLIPREENCH_EMAIL = "CLIPREENCH_EMAIL"
Public Const FATCFG_CLIPREENCH_CONTATO = "CLIPREENCH_CONTATO"

'#########################################
'Inserido por Wagner
Public Const FATCFG_TEM_VERSAO_OV = "TEM_VERSAOKIT_ORCAMENTOVENDA"
Public Const TEM_VERSAO_OV = 1
Public Const NAO_TEM_VERSAO_OV = 0
'#########################################

Public Const FATCFG_BROWSE_FECHA = "BROWSE_FECHA"
Public Const FATCFG_TIPO_VALIDACAO_PRJ = "TIPO_VALIDACAO_PROJETOS"
Public Const FATCFG_DIR_GERACAO_RPS = "DIR_GERACAO_RPS"

Public Const FATCFG_COTAR_ITENS_ORCVENDA = "COTAR_ITENS_ORCVENDA"
Public Const FATCFG_ABATE_ICMSSUBST_VALOR_COBRANCA = "ABATE_ICMSSUBST_VALOR_COBRANCA"
Public Const FATCFG_IMPEDE_IMP_PV_COM_BLOQ = "IMPEDE_IMPRESSAO_PV_COM_BLOQ"
Public Const FATCFG_FALTA_ESTOQUE_OBRIGA_TOMADA_DECISAO = "FALTA_ESTOQUE_OBRIGA_TOMADA_DECISAO"
Public Const FATCFG_TEM_FAIXA_RECEB = "TEM_FAIXA_RECEB"
Public Const FATCFG_PERCENT_MAIS_RECEB = "PERCENT_MAIS_RECEB"
Public Const FATCFG_PERCENT_MENOS_RECEB = "PERCENT_MENOS_RECEB"
Public Const FATCFG_RECEB_FORA_FAIXA = "RECEB_FORA_FAIXA"
Public Const FATCFG_EXIBE_PERCFAT_PV = "EXIBE_PERCFAT_PV"
Public Const FATCFG_VENDA_FORA_EST_USA_TALAO_MANUAL = "VENDA_FORA_EST_USA_TALAO_MANUAL"
Public Const FATCFG_GERACAO_FATURA_TODAS_FILIAIS = "GERACAO_FATURA_TODAS_FILIAIS"
Public Const FATCFG_EXIBE_ROTAS_CLIENTE = "EXIBE_ROTAS_CLIENTE"
Public Const FATCFG_POSSUI_INTEGRACAO_MAPLINK = "POSSUI_INTEGRACAO_MAPLINK"
Public Const FATCFG_IMPORTACAO_COM_DADOS_INTERNOS = "IMPORTACAO_COM_DADOS_INTERNOS"
Public Const FATCFG_PULA_LINHA_GRADE = "PULA_LINHA_GRADE"
Public Const FATCFG_IMPRIME_PV_GRAVACAO = "IMPRIME_PV_GRAVACAO"
Public Const FATCFG_NATUREZAOP_NF_TIPO_226_GOVERNO = "NATUREZAOP_NF_TIPO_226_GOVERNO"
Public Const FATCFG_CLIENTE_NF_TIPO_226_GOVERNO = "CLIENTE_NF_TIPO_226_GOVERNO"
Public Const FATCFG_CLIENTE_NFCE_SEM_CPF = "CLIENTE_NFCE_SEM_CPF"
Public Const FATCFG_TRAZ_DESCONTO_PV_PARA_NF = "TRAZ_DESCONTO_PV_PARA_NF"
Public Const FATCFG_EXIBE_OPCAO_IMPRIMIR_OV_SEM_PRECO = "EXIBE_OPCAO_IMPRIMIR_OV_SEM_PRECO"
Public Const FATCFG_INATIVA_CLIENTE_DIAS_SEM_COMPRA = "INATIVA_CLIENTE_DIAS_SEM_COMPRA"
Public Const FATCFG_EXIBE_DATA_SAIDA_NF = "EXIBE_DATA_SAIDA_NF"
Public Const FATCFG_DIR_IMPORT_PV_SOC = "DIR_IMPORT_PV_SOC"
Public Const FATCFG_EXIBE_OPCAO_IMPRIMIR_OV_COM_CODPROD = "EXIBE_OPCAO_IMPRIMIR_OV_COM_CODPROD"
Public Const FATCFG_EXIBE_OPCAO_OV_CALCULAR_ST = "EXIBE_OPCAO_OV_CALCULAR_ST"
Public Const FATCFG_CALCULAR_ST_OP_PADRAO = "CALCULAR_ST_OP_PADRAO"
Public Const FATCFG_PRIM_PARC_ICMSST = "FATCFG_PRIM_PARC_ICMSST"
Public Const FATCFG_PRIM_PARC_IPI = "FATCFG_PRIM_PARC_IPI"
Public Const FATCFG_PRIM_PARC_PISST = "FATCFG_PRIM_PARC_PISST"
Public Const FATCFG_PRIM_PARC_COFINSST = "FATCFG_PRIM_PARC_COFINSST"
Public Const FATCFG_TRATA_NF_DEV_SIMB_BENEF_POR_OP = "TRATA_NF_DEV_SIMB_BENEF_POR_OP"
Public Const FATCFG_NF_DEV_SIMB_BENEF_SUGERIR_OPS = "NF_DEV_SIMB_BENEF_SUGERIR_OPS"
Public Const FATCFG_NF_DEV_SIMB_BENEF_ALM_SOBRA = "NF_DEV_SIMB_BENEF_ALM_SOBRA"
Public Const FATCFG_NF_DEV_SIMB_UM = "NF_DEV_SIMB_UM"

Public Const FATCFG_OV_EXIBE_ORDENACAO_ITENS = "OV_EXIBE_ORDENACAO_ITENS"
Public Const FATCFG_OV_EXIBE_TOTAL_SELECIONADO = "OV_EXIBE_TOTAL_SELECIONADO"

Public Const FATCFG_OV_ACOMP_FILTRA_VENDEDOR = "OV_ACOMP_FILTRA_VENDEDOR"
Public Const FATCFG_OV_SEM_FORM_PRECO = "OV_SEM_FORM_PRECO"
Public Const FATCFG_PESOS_RECALCULA = "PESOS_RECALCULA"
Public Const FATCFG_OV_ACOMP_FILTRO_VENDEDOR_OBRIGATORIO = "OV_ACOMP_FILTRO_VENDEDOR_OBRIGATORIO"
Public Const FATCFG_USA_PARCELAMENTO_DO_PV = "USA_PARCELAMENTO_DO_PV"

Public Const FATCFG_EXIBE_TABPRECO_ITENSPV = "EXIBE_TABPRECO_ITENSPV"
Public Const FATCFG_EXIBE_COMISSAO_ITENSPV = "EXIBE_COMISSAO_ITENSPV"
Public Const FATCFG_EXIBE_QTDECANCELADA_ITENSPV = "EXIBE_QTDECANCELADA_ITENSPV"
Public Const FATCFG_ATUALIZA_PLACAPV_MAPAENTREGA = "ATUALIZA_PLACAPV_MAPAENTREGA"
Public Const FATCFG_USA_COMISSAO_POR_ITEM = "USA_COMISSAO_POR_ITEM"

Public Const FATCFG_KIT_VENDA_EXIBE_COMPONENTES = "KIT_VENDA_EXIBE_COMPONENTES"
Public Const FATCFG_EXIBE_BTN_EXPORTA_PV = "EXIBE_BTN_EXPORTA_PV"
Public Const FATCFG_ZERA_QTDE_EM_NF_COMPL_PRECO = "ZERA_QTDE_EM_NF_COMPL_PRECO"

Public Const FATCFG_PACREC_COBRA_ST_NOVA_PARC = "PACREC_COBRA_ST_NOVA_PARC"
Public Const FATCFG_PARC_ST_NUM_DIAS = "PARC_ST_NUM_DIAS"
Public Const FATCFG_OBRIGA_PREENCH_PRJ = "OBRIGA_PREENCH_PRJ"
Public Const FATCFG_OV_BLOQUEIA_EDIT_DESCPROD = "OV_BLOQUEIA_EDIT_DESCPROD"
Public Const FATCFG_NF_FATURA_APENAS_O_RESERVADO_NO_PV = "NF_FATURA_APENAS_O_RESERVADO_NO_PV"
Public Const FATCFG_PRJ_EXIBE_VISTORIA_ETAPAS = "PRJ_EXIBE_VISTORIA_ETAPAS"
Public Const FATCFG_PRJ_TIPO_PRAZO_VALIDADE_VISTORIA = "PRJ_TIPO_PRAZO_VALIDADE_VISTORIA"
Public Const FATCFG_PRJ_PRAZO_VALIDADE_VISTORIA = "PRJ_PRAZO_VALIDADE_VISTORIA"
Public Const FATCFG_CHVNFE_VALIDA_CNPJ = "CHVNFE_VALIDA_CNPJ"
Public Const FATCFG_PVPREENCH_DATAENTREGA = "PVPREENCH_DATAENTREGA"

'chaves em CRFATConfig

'Alteracao Daniel
Public Const CRFATCFG_COD_FORNECEDOR_RECEITA = "COD_FORNECEDOR_RECEITA"

Public Const CRFATCFG_COD_CLIENTE_EMP = "COD_CLIENTE_EMP"
Public Const CRFATCFG_COD_FORNECEDOR_EMP = "COD_FORNECEDOR_EMP"
Public Const CRFATCFG_USA_COMISSOES_REGRAS = "USA_COMISSOES_REGRAS" 'Incluido por Leo em 15/03/02
Public Const CRFATCFG_USA_NFE = "USA_NFE"
Public Const CRFATCFG_GRAVA_NFE = "GRAVA_NFE"
Public Const CRFATCFG_USA_NFSE = "USA_NFSE"
Public Const CRFATCFG_GRAVA_NFSE = "GRAVA_NFSE"
Public Const CRFATCFG_DIAS_BLOQUEIO_ATRASO = "DIAS_BLOQUEIO_ATRASO" 'Incluido por Leo em 26/02/02
Public Const CRFATCFG_CREDITO_VERIFICA_LIMITE = "CREDITO_VERIFICA_LIMITE" 'tulio130103
Public Const CRFATCFG_ISS_NA_BASE = "ISS_NA_BASE"
Public Const CRFATCFG_IPI_ABATE_DESCONTO = "IPI_ABATE_DESCONTO"
Public Const CRFATCFG_CONDPAGTO_SEM_CODIGO = "CONDPAGTO_SEM_CODIGO"
Public Const CRFATCFG_DESCONTO_PADRAO_CODIGO1 = "DESCONTO_PADRAO_CODIGO1"
Public Const CRFATCFG_DESCONTO_PADRAO_CODIGO2 = "DESCONTO_PADRAO_CODIGO2"
Public Const CRFATCFG_DESCONTO_PADRAO_CODIGO3 = "DESCONTO_PADRAO_CODIGO3"
Public Const CRFATCFG_DESCONTO_PADRAO_DIAS1 = "DESCONTO_PADRAO_DIAS1"
Public Const CRFATCFG_DESCONTO_PADRAO_DIAS2 = "DESCONTO_PADRAO_DIAS2"
Public Const CRFATCFG_DESCONTO_PADRAO_DIAS3 = "DESCONTO_PADRAO_DIAS3"
Public Const CRFATCFG_DESCONTO_PADRAO_PERCENTUAL1 = "DESCONTO_PADRAO_PERCENTUAL1"
Public Const CRFATCFG_DESCONTO_PADRAO_PERCENTUAL2 = "DESCONTO_PADRAO_PERCENTUAL2"
Public Const CRFATCFG_DESCONTO_PADRAO_PERCENTUAL3 = "DESCONTO_PADRAO_PERCENTUAL3"
Public Const CRFATCFG_JUROS_PADRAO = "JUROS_PADRAO"
Public Const CRFATCFG_MULTA_PADRAO = "MULTA_PADRAO"
Public Const CRFATCFG_NUM_PROX_ITEM_NOTA_FISCAL = "NUM_PROX_ITEM_NOTA_FISCAL"
Public Const CRFATCFG_NUM_PROX_NOTA_FISCAL = "NUM_PROX_NOTA_FISCAL"
Public Const CRFATCFG_NUM_PROX_NOTA_FISCAL_FATURA = "NUM_PROX_NOTA_FISCAL_FATURA"
Public Const CRFATCFG_NUM_PROX_OCREMPARC = "NUM_PROX_OCREMPARC"
Public Const CRFATCFG_NUM_PROX_OCRETPARC = "NUM_PROX_OCRETPARC"
Public Const CRFATCFG_NUM_TABELA_PRECO = "NUM_PROX_TABELA_PRECO"
Public Const CRFATCFG_NUM_PROX_TRANSFCARTCOBR = "NUM_PROX_TRANSFCARTCOBR"
Public Const CRFATCFG_FATURA_IMPRIMINDO = "FATURA_IMPRIMINDO"
Public Const CRFATCFG_FATURA_LOCKIMPRESSAO = "FATURA_LOCKIMPRESSAO"
Public Const CRFATCFG_FATURA_NUM_PROX = "FATURA_NUM_PROX"
Public Const CRFATCFG_FATURA_NUM_PROX_IMPRESSAO = "FATURA_NUM_PROX_IMPRESSAO"
Public Const CRFATCFG_PERMITE_MULTA_SEM_ATRASO = "PERMITE_MULTA_SEM_ATRASO"
Public Const CRFATCFG_VALIDA_BORDERO_PAGTO = "VALIDA_BORDERO_PAGTO"
Public Const CRFATCFG_TAXAFINANCEIRA_PADRAO = "TAXAFINANCEIRA_PADRAO"
Public Const CRFATCFG_BLOQUEARPV_PRECO_BAIXO = "BLOQUEARPV_PRECO_BAIXO"
Public Const CRFATCFG_BLOQUEARPV_MARGEM_BAIXA = "BLOQUEARPV_MARGEM_BAIXA"
Public Const CRFATCFG_BLOQUEARPV_PRECO_DEFASADO = "BLOQUEARPV_PRECO_DEFASADO"
Public Const CRFATCFG_DIRETORIO_BOLETO_GERACAO = "DIRETORIO_BOLETO_GERACAO"
Public Const CRFATCFG_ENVIA_EMAIL_COM_CONFIRMACAO_DE_RECEBTO = "ENVIA_EMAIL_COM_CONFIRMACAO_DE_RECEBTO"
Public Const CRFATCFG_PROD_REPETIDO_NF = "PROD_REPETIDO_NF"
Public Const CRFATCFG_PROD_REPETIDO_PV = "PROD_REPETIDO_PV"
Public Const CRFATCFG_PROD_REPETIDO_OV = "PROD_REPETIDO_OV"
Public Const CRFATCFG_OV_GRAVACAO_VERSAO = "OV_GRAVACAO_VERSAO"
Public Const CRFATCFG_COMISSAO_RETIRA_CREDITO_IMPOSTOS = "COMISSAO_RETIRA_CREDITO_IMPOSTOS"
Public Const CRFATCFG_SEPARA_ITENSGRADE_PRECO_DIF = "SEPARA_ITENSGRADE_PRECO_DIF"
Public Const CRFATCFG_NAO_TESTAR_NFE = "NAO_TESTAR_NFE"
Public Const CRFATCFG_NAO_TESTAR_NFE_PESO_VOLUME = "NAO_TESTAR_NFE_PESO_VOLUME"
Public Const CRFATCFG_VERSAO_LAYOUT_NFE = "VERSAO_LAYOUT_NFE"
Public Const CRFATCFG_ICMSST_COM_IE_ISENTO = "ICMSST_COM_IE_ISENTO"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG01 = "NF_IMPORTACAO_TRB_FLAG01"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG02 = "NF_IMPORTACAO_TRB_FLAG02"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG03 = "NF_IMPORTACAO_TRB_FLAG03"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG04 = "NF_IMPORTACAO_TRB_FLAG04"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG05 = "NF_IMPORTACAO_TRB_FLAG05"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG06 = "NF_IMPORTACAO_TRB_FLAG06"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG07 = "NF_IMPORTACAO_TRB_FLAG07"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG08 = "NF_IMPORTACAO_TRB_FLAG08"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG09 = "NF_IMPORTACAO_TRB_FLAG09"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG10 = "NF_IMPORTACAO_TRB_FLAG10"

Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG11 = "NF_IMPORTACAO_TRB_FLAG11"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG12 = "NF_IMPORTACAO_TRB_FLAG12"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG13 = "NF_IMPORTACAO_TRB_FLAG13"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG14 = "NF_IMPORTACAO_TRB_FLAG14"
Public Const CRFATCFG_NF_IMPORTACAO_TRB_FLAG15 = "NF_IMPORTACAO_TRB_FLAG15"

Public Const CRFATCFG_NF_TESTA_SOMATORIOS = "NF_TESTA_SOMATORIOS"
Public Const CRFATCFG_CLI_ATRASO_DESTACAR = "CRFATCFG_CLI_ATRASO_DESTACAR"
Public Const CRFATCFG_CLI_ATRASO_NAO_GRAVAR_PV = "CRFATCFG_CLI_ATRASO_NAO_GRAVAR_PV"
Public Const CRFATCFG_DIR_IMPORT_XML_NFE = "DIR_IMPORT_XML_NFE"
Public Const CRFATCFG_NF_IMPORTACAO_XML = "NF_IMPORTACAO_XML"
Public Const CRFATCFG_NF_IMPORTACAO_XML_PROD = "NF_IMPORTACAO_XML_PROD"
Public Const CRFATCFG_TRIB_IPI_NAO_INCIDE = "TRIB_IPI_NAO_INCIDE"
Public Const CRFATCFG_TRIB_ICMS_PFFORAEST = "TRIB_ICMS_PFFORAEST"
Public Const CRFATCFG_TRIB_CALCSTCOBRANT = "TRIB_CALCSTCOBRANT"
Public Const CRFATCFG_EXTENSAO_GER_REL_EXPORTA = "EXTENSAO_GER_REL_EXPORTA"
Public Const CRFATCFG_TITPAG_VERIFICA_REPETICAO_SEM_SIGLA = "TITPAG_VERIFICA_REPETICAO_SEM_SIGLA"
Public Const CRFATCFG_DATA_RESOLUCAO_13_SENADO = "DATA_RESOLUCAO_13_SENADO"
Public Const CRFATCFG_DATA_EC_87_2015 = "DATA_EC_87_2015"
Public Const CRFATCFG_TOT_TRIB_TIPO = "TOT_TRIB_TIPO"
Public Const CRFATCFG_TOT_TRIB_CNPJ = "TOT_TRIB_CNPJ"
Public Const CRFATCFG_ICMS_PROTOCOLO_21 = "ICMS_PROTOCOLO_21"
Public Const CRFATCFG_EC_87_2015_TESTE = "EC_87_2015_TESTE"
Public Const CRFATCFG_EC_87_2015_SIMPLES = "EC_87_2015_SIMPLES"
Public Const CRFATCFG_OTIMIZA_TRIBUTACAO = "OTIMIZA_TRIBUTACAO"
Public Const CRFATCFG_CRIAR_PAG_SUSPENSO = "CRIAR_PAG_SUSPENSO"

Public Const CRFATCFG_INFOADIC_NATUREZA_OBRIGATORIA = "INFOADIC_NATUREZA_OBRIGATORIA"
Public Const CRFATCFG_INFOADIC_CCL_OBRIGATORIA = "INFOADIC_CCL_OBRIGATORIA"

Public Const CRFATCFG_VALIDA_DESC_MAX_TAB_PRECO = "VALIDA_DESC_MAX_TAB_PRECO"
Public Const CRFATCFG_USA_BLOQ_ACESSO_POR_TELA_CONTROLE = "USA_BLOQ_ACESSO_POR_TELA_CONTROLE"
Public Const CRFATCFG_CALCULA_CFOP_ITEM = "CALCULA_CFOP_ITEM"
Public Const CRFATCFG_ACAO_TESTE_CFOP_TIPONF = "ACAO_TESTE_CFOP_TIPONF"
Public Const CRFATCFG_NFE_SISTEMA_CONTINGENCIA = "NFE_SISTEMA_CONTINGENCIA"
Public Const CRFATCFG_PRECO_UNITARIO_FORM_PRECO = "PRECO_UNITARIO_FORM_PRECO"
Public Const CRFATCFG_PISCOFINS_SIMPLES_99 = "PISCOFINS_SIMPLES_99"
Public Const CRFATCFG_VENDA_FUTURA_TRIBUTACAO = "VENDA_FUTURA_TRIBUTACAO"
Public Const CRFATCFG_TRIB_TRATA_ST_ENTRADA_EM_CST00 = "TRIB_TRATA_ST_ENTRADA_EM_CST00"
Public Const CRFATCFG_CNAB_CEF_NOME_INI_COM_E = "CNAB_CEF_NOME_INI_COM_E"
Public Const CRFATCFG_IPI_INICIO_EXCLUSAO_DESC_DA_BASE = "IPI_INICIO_EXCLUSAO_DESC_DA_BASE"
Public Const CRFATCFG_ICMS_INCLUI_IPI_BASE_CONSUMIDOR_FINAL = "ICMS_INCLUI_IPI_BASE_CONSUMIDOR_FINAL"

Public Const CRFATCFG_IPI_CALCULO_VLR_DEVOLVIDO = "IPI_CALCULO_VLR_DEVOLVIDO"
Public Const CRFATCFG_PIS_TIPO_CALCULO_NO_SIMPLES = "PIS_TIPO_CALCULO_NO_SIMPLES"

Public Const DESC_CRFATCFG_DIR_IMPORT_XML_NFE = "Localização do diretório contendo xml de NFe para importação por filial empresa"

Public Const VALIDA_BORDERO_PAGTO_CRIACAO = 1
Public Const VALIDA_BORDERO_PAGTO_GERA_ARQ = 0

'Chaves em CPConfig
Public Const CPCFG_AGLUTINA_LANCAM_POR_DIA = "AGLUTINA_LANCAM_POR_DIA"
Public Const CPCFG_GERA_LOTE_AUTOMATICO = "GERA_LOTE_AUTOMATICO"
Public Const CPCFG_CPR_CONTAB_SEM_DET = "CPR_CONTAB_SEM_DET"
Public Const CPCFG_FILIAL_CENTRALIZADORA = "FILIAL_CENTRALIZADORA"

'Chaves em CRConfig
Public Const CRCFG_AGLUTINA_LANCAM_POR_DIA = "AGLUTINA_LANCAM_POR_DIA"
Public Const CRCFG_GERA_LOTE_AUTOMATICO = "GERA_LOTE_AUTOMATICO"
Public Const CRCFG_FILIAL_CENTRALIZADORA = "FILIAL_CENTRALIZADORA"
Public Const CRCFG_NUM_PROX_ID_BOLETO = "NUM_PROX_ID_BOLETO"
Public Const CRCFG_CR_CONTAB_SEM_DET = "CR_CONTAB_SEM_DET"
Public Const CRCFG_CR_IRRF_LANCAM_BAIXA = "CR_IRRF_LANCAM_BAIXA"
Public Const CRCFG_VERIFICA_CHEQUES_MESMA_CONTA = "VERIFICA_CHEQUES_MESMA_CONTA"

'Chaves em TESConfig
Public Const TESCFG_AGLUTINA_LANCAM_POR_DIA = "AGLUTINA_LANCAM_POR_DIA"
Public Const TESCFG_GERA_LOTE_AUTOMATICO = "GERA_LOTE_AUTOMATICO"
Public Const TESCFG_FLUXO_INCLUI_PEDIDOS = "FLUXO_INCLUI_PEDIDOS"
Public Const TESCFG_MOVCC_VERIFICA_BLOQUEIO_DATA = "MOVCC_VERIFICA_BLOQUEIO_DATA"
Public Const TESCFG_MOVCC_BLOQUEIO_DATA_LIMITE = "MOVCC_BLOQUEIO_DATA_LIMITE"

'Chaves em ESTConfig
Public Const ESTCFG_AGLUTINA_LANCAM_POR_DIA = "AGLUTINA_LANCAM_POR_DIA"
Public Const ESTCFG_GERA_LOTE_AUTOMATICO = "GERA_LOTE_AUTOMATICO"
Public Const ESTCFG_INCLUI_FRETE_CUSTO = "INCLUI_FRETE_CUSTO"
Public Const ESTCFG_ACEITA_ESTOQUE_NEGATIVO = "ACEITA_ESTOQUE_NEGATIVO"
Public Const ESTCFG_OP_DETALHAMENTO_RCS = "OP_DETALHAMENTO_RCS"
Public Const ESTCFG_OP_EMPENHA_EMBALAGEM = "OP_EMPENHA_EMBALAGEM"
Public Const ESTCFG_TRATA_EST_TERC_CLI_FORN = "TRATA_EST_TERC_CLI_FORN"
Public Const ESTCFG_ACEITA_EAN_REPETIDO = "ACEITA_EAN_REPETIDO"

Public Const ESTCFG_OP_VALIDA_REPETICAO_ITEM = "OP_VALIDA_REPETICAO_ITEM"
Public Const ESTCFG_ACEITA_KIT_PRODUTO_GERENCIAL = "ACEITA_KIT_PROD_GERENCIAL"

Public Const ESTCFG_TAMANHO_MINIMO_PRODUTO_GRID = "TAMANHO_MINIMO_PRODUTO_GRID"
Public Const ESTCFG_TAMANHO_MINIMO_CONTA_GRID = "TAMANHO_MINIMO_CONTA_GRID"

Public Const ESTCFG_TESTA_INT_ESTPRODUTO = "TESTA_INT_ESTPRODUTO"
Public Const ESTCFG_TESTA_INT_ESTNEGATIVO = "TESTA_INT_ESTNEGATIVO"
Public Const ESTCFG_TESTA_INT_SALDOS = "TESTA_INT_SALDOS"
Public Const ESTCFG_TESTA_INT_ACAO = "TESTA_INT_ACAO"
Public Const ESTCFG_TESTA_INT_DIR_ARQ_LOG = "TESTA_INT_DIR_ARQ_LOG"
Public Const ESTCFG_PROD_FATOR_AJUSTE = "PROD_FATOR_AJUSTE"
Public Const ESTCFG_MOVEST_VERIFICA_BLOQUEIO_DATA = "MOVEST_VERIFICA_BLOQUEIO_DATA"
Public Const ESTCFG_MOVEST_BLOQUEIO_DATA_LIMITE = "MOVEST_BLOQUEIO_DATA_LIMITE"
Public Const ESTCFG_OP_TIPO_CALC_NECESSIDADE = "OP_TIPO_CALC_NECESSIDADE"

Public Const ESTCFG_BLOQUEIA_ALTER_DATA_ESTINI_ANOPOST = "BLOQUEIA_ALTER_DATA_ESTINI_ANOPOST"
Public Const ESTCFG_BLOQUEIA_DATA_DIF_ESTINI_PROD = "BLOQUEIA_DATA_DIF_ESTINI_PROD"
Public Const ESTCFG_BLOQUEIA_DATA_DIF_ESTINI = "BLOQUEIA_DATA_DIF_ESTINI"
Public Const ESTCFG_BLOQUEIA_VALOR_ZERADO_ESTINI = "BLOQUEIA_VALOR_ZERADO_ESTINI"
Public Const ESTCFG_REQPROD_CONSIDERA_PERCPERDA = "REQPROD_CONSIDERA_PERCPERDA"
Public Const ESTCFG_CONTAB_PELA_DATA_ENTRADA_XML = "CONTAB_PELA_DATA_ENTRADA_XML"

Public Const NAO_GERA_LOTE_AUTOMATICO = 0
Public Const GERA_LOTE_AUTOMATICO = 1

Public Const NAO_AGLUTINA_LANCAM_POR_DIA = 0
Public Const AGLUTINA_LANCAM_POR_DIA = 1

Public Const NAO_INCLUI_FRETE_CUSTO = 0
Public Const INCLUI_FRETE_CUSTO = 1

Public Const LANCAMENTO_NAO_AGLUTINADO = 0
Public Const LANCAMENTO_AGLUTINA = 1 'serve para indicar que um lançamento será armazenado aglutinadamente por dia
Public Const LANCAMENTO_AGLUTINADO = 2 'serve para indicar que um lançamento armazena dados aglutinados por conta/dia a partir de varios lançamentos

Public Const LANCAMENTO_STATUS_NAO_GERENCIAL = 0
Public Const LANCAMENTO_STATUS_GERENCIAL = 1
Public Const LANCAMENTO_STATUS_AMBOS = 2

'Constante incluida por tulio em 12/04
Public Const TITULO_TAB_COMISSOES = "Comissões"

Public Const TITULO_TAB_CONTABILIDADE = "Contabilização"
Public Const CONTABILIDADE_ALTERADA = 1 'indica que foi alterado pelo usuário alguma info de contabilidade na tela

Public Const ROTINA_ATUALIZACAO_BATCH = 1
Public Const ROTINA_APURA_EXERCICIO_BATCH = 2
Public Const ROTINA_APURA_PERIODOS_BATCH = 3
Public Const ROTINA_FECHAMENTO_EXERCICIO_BATCH = 4
Public Const ROTINA_REABERTURA_EXERCICIO_BATCH = 5
Public Const ROTINA_REPROCESSAMENTO_BATCH = 6
Public Const ROTINA_ATUALIZACAO_ONLINE = 7
Public Const ROTINA_RATEIOOFF_BATCH = 8
Public Const ROTINA_REPROC_CUSTO_MEDIO = 9
Public Const ROTINA_REPROC_CUSTO_PRODUCAO = 10
Public Const ROTINA_EXCLUSAO_LANCAMENTOS = 11
Public Const ROTINA_DESAPURA_EXERCICIO_BATCH = 12
Public Const ROTINA_SPED_DIARIO = 13
Public Const ROTINA_FCONT = 14


Public Const TITULO_TELABATCH_ATUALIZA_LOTE = "Atualização de Lote"
Public Const TITULO_TELABATCH_APURA_PERIODO = "Apuração de Período"
Public Const TITULO_TELABATCH_APURA_EXERCICIO = "Apuração de Exercício"
Public Const TITULO_TELABATCH_REPROCESSAMENTO = "Reprocessamento"
Public Const TITULO_TELABATCH_FECHA_EXERCICIO = "Fechamento de Exercício"
Public Const TITULO_TELABATCH_REABRE_EXERCICIO = "Reabertura de Exercício"
Public Const TITULO_TELABATCH_RATEIOOFF = "Rateio Off-Line"
Public Const TITULO_TELABATCH_DESAPURA_EXERCICIO = "Desapuração de Exercício"
Public Const TITULO_SPED_DIARIO = "Diário - Sped"
Public Const TITULO_FCONT = "FCONT"

Public Const INCLUI_CONTA_SALDO_INICIAL = 1
Public Const INCLUI_CCL_SALDO_INICIAL = 1
Public Const CONTACATEGORIA_APURACAO = 1
Public Const GRID_CONTA_COL = 1
Public Const GRID_PERCENTUAL_COL = 2
Public Const TIPO_CCL = 1

Public Const CCL_TEM_FILHOS = 1
Public Const CCL_NAO_TEM_FILHOS = 0

Public Const ITEM_TEM_FILHOS = 1
Public Const ITEM_NAO_TEM_FILHOS = 0

'Codigos de CTBConfig
Public Const CONTA_RESULTADO_EXERCICIO = "CONTA_RESULTADO_EXERCICIO"
Public Const CONTA_TRANSFERENCIA_FILIAL = "CONTA_TRANSFERENCIA_FILIAL"
Public Const CONTA_PRODUCAO_FILIAL = "CONTA_PRODUCAO_FILIAL"
Public Const HISTORICO_CTB_OBRIGATORIO = "HISTORICO_CTB_OBRIGATORIO"
Public Const VALIDA_CONTA_CCL = "VALIDA_CONTA_CCL"
Public Const PLANOCTBREF_VALIDA_CONTA_CCL = "PLANOCTBREF_VALIDA_CONTA_CCL"
Public Const CTB_LANCAMENTO_EXCLUI_EFETIVO_ESTORNO = "CTB_LANCAMENTO_EXCLUI_EFETIVO_ESTORNO"

'Categorias de Conta
Public Const CONTACATEGORIA_ATIVO = "Ativo"
Public Const CONTACATEGORIA_PASSIVO = "Passivo"
Public Const CONTACATEGORIA_RECEITA = "Receita"
Public Const CONTACATEGORIA_DESPESA = "Despesa"
Public Const CONTACATEGORIA_RESULTADO_EXERCICIO = "Resultado_Exercicio"

'Formato inicial da tela de segmento
Public Const SEGMENTO_CONTA = "conta"
Public Const SEGMENTO_CCL = "ccl"
Public Const SEGMENTO_PRODUTO = "produto"
Public Const SEGMENTO_NATMOVCTA = "natureza"
Public Const SEGMENTO_PROJETO = "Projeto"
Public Const SEGMENTO_REFETAPA = "RefEtapa"
Public Const SEGMENTO_CONTAREF = "contaref"

Global Const SLDINI_DISPONIVEL = 1
Global Const SLDINI_NAO_DISPONIVEL = 0

Global Const CONTA_VAZIA = 0
Global Const CONTA_PREENCHIDA = 1
Global Const CCL_PREENCHIDA = 1
Global Const CCL_VAZIA = 0

'Status de Conta Contábil
Global Const CONTA_ATIVA = 0
Global Const CONTA_INATIVA = 1

Global Const CONTA_USA_DIGITOVERIF = 1
Global Const CONTA_NAO_USA_DIGITOVERIF = 0

Global Const CONTA_USA_DIGITOVERIFSIMPLES = 1
Global Const CONTA_NAO_USA_DIGITOVERIFSIMPLES = 0

Global Const CONTA_USA_CONTASIMPLES = 1
Global Const CONTA_NAO_USA_CONTASIMPLES = 0

Global Const CONTA_CREDITO = 1
Global Const CONTA_DEBITO = 2

'Tipo de Operação
Global Const ATUALIZACAO = 1
Global Const DESATUALIZACAO = -1

'Status de Lote
Global Const LOTE_ATUALIZADO = 1
Global Const LOTE_DESATUALIZADO = 0
Global Const LOTE_INCOMPLETO = 2
Global Const LOTE_NAO_ATUALIZADO = 0
'Quando a coluna Id_Atualizacao = 0 na tabela LotePendente
Global Const LOTE_ATUALIZANDO = 3
'Status do lote na tela de atualização de lote quando o lote se encontra em processo de atualização
Global Const LOTE_ATUALIZANDO_TEXTO = "Atualizando"
'Numero de linhas do grid LotePendente

'Status de Exercicio
Global Const EXERCICIO_ABERTO = 1
Global Const EXERCICIO_APURADO = 2
Global Const EXERCICIO_FECHADO = 3

'Descriçao do Status do Exercicio
Public Const EXERCICIO_DESC_ABERTO = "Aberto"
Public Const EXERCICIO_DESC_APURADO = "Apurado"
Public Const EXERCICIO_DESC_FECHADO = "Fechado"

'Status de Periodo
Global Const PERIODO_ABERTO = 0
Global Const PERIODO_FECHADO = 1

'Apuracao de Periodo
Global Const PERIODO_APURADO = 1
Global Const PERIODO_NAO_APURADO = 0

'Tipo da Conta
Global Const CONTA_SINTETICA = 1
Global Const CONTA_ANALITICA = 3

'Tipo de Centro de Custo/Lucro
Public Const CCL_SINTETICA = 1
Public Const CCL_ANALITICA = 3

'Tipo de Preenchimento do Segmento da Conta
Global Const ZEROS_ESPACOS = 1
Global Const ESPACOS = 0
Global Const PREENCH_LIMPA_BRANCOS = 2

'Presenca dos Lancamentos (tabela Periodos)
Global Const LANCAMENTOS_NO_BD = 1
Global Const LANCAMENTO_FORA_BD = 0

'Caracter que indica Histórico Padrão
Public Const CARACTER_HISTPADRAO As String = "*"

'Caracter que indica Parametro de Historico
Public Const CARACTER_HISTORICO_PARAM As String = "?"

'Caracter que indica que um mnemônico deve ser executado para todas as linhas do grid
Public Const CARACTER_TODAS_LINHAS_GRID = "[*]"

'Limitações de GRID, BROWSES, ComboBoxes e outros
Global Const MAX_LANCAMENTOS_POR_DOC = 1000
Global Const MAX_LANCAMENTOS_POR_DOC_CTB = 10000
Global Const MAX_LOTES_ABERTOS = 100
Global Const MAX_ORIGENS = 20
Global Const NUM_MAX_PERIODOS = 12

'Limites para alteração nas linhas do Grid
Global Const PROIBIDO_EXCLUIR = 1
Global Const PROIBIDO_INCLUIR = 1
    
'Índice Default para ComboBoxes
Global Const COMBO_INDICE = -1
    
'Status da Existencia de Lote de Apuracao de Exercicio
Public Const EXISTE_LOTE_APURACAO_EXERCICIO = 1
Public Const NAO_EXISTE_LOTE_APURACAO_EXERCICIO = 0

'Status da Existencia de Lote de Apuracao de Periodo
Public Const EXISTE_LOTE_APURACAO_PERIODO = 1
Public Const NAO_EXISTE_LOTE_APURACAO_PERIODO = 0

'Grid Lotes
Global Const LOTE_LARG = 510
Global Const PERIODO_LARG = 735
Global Const ORIGEM_LARG = 675
Global Const STATUS_LOTE_LARG = 630

'PadraoContab - indica se é o modelo padrao ou nao
Public Const PADRAOCONTAB_MODELO_PADRAO = 1
Public Const PADRAOCONTAB_NAO_E_MODELO_PADRAO = 0

'PadraoContab
Public Const PADRAOCONTABITEM_NORMAL = 0
Public Const PADRAOCONTABITEM_CUSTO = 1

'Relatórios
Public Const Imprimir = 0
Public Const PREVIEW = 2

'Limite da Versao Ligth
Public Const LIMITE_CCL_VLIGHT = 5

'Tamanhos de Strings no BD
Global Const STRING_CONTA_MAIS_UM = STRING_CONTA + 1
Global Const STRING_CCL = 10
Global Const STRING_CCL_MAIS_UM = STRING_CCL + 1
'Global Const STRING_ORIGEM = 3
Global Const STRING_HISTORICO = 150
Global Const STRING_HISTORICO_MAIS_UM = STRING_HISTORICO + 1
Public Const STRING_DOCORIGEM_MAIS_UM = STRING_DOCORIGEM + 1
Global Const STRING_CODIGO_HISTORICO = 4
'Global Const STRING_ORIGEM_DESCRICAO = 30
Global Const STRING_IDORIGINAL = 20
Global Const STRING_CONTA_DESCRICAO = 40
Global Const STRING_PERIODO_NOME_EXTERNO = 20
Global Const STRING_CCL_DESCRICAO = 100
Global Const STRING_EXERCICIO_NOME_EXTERNO = 20
Global Const STRING_CONTA_MASK = 100
Global Const STRING_CCL_MASK = 100
Global Const STRING_DOCAUTO_DESCRICAO = 40
Global Const STRING_RATEIO_DESCRICAO = 40
Global Const POSSUI_CONTA = 1
Global Const NAO_POSSUI_CONTA = 0
Public Const POSSUI_CCL = 1
Public Const NAO_POSSUI_CCL = 0
Global Const STRING_SEGMENTO_CODIGO = 10
Global Const STRING_NOME_EXTERNO = 30
Public Const STRING_CONTA_CATEGORIA_NOME = 50
Public Const STRING_CONTA_CATEGORIA_CODIGO = 4
Public Const STRING_CTBCONFIG_CODIGO = 50
Public Const STRING_CTBCONFIG_DESCRICAO = 150
Public Const STRING_CTBCONFIG_CONTEUDO = 255
Public Const STRING_PADRAOCONTAB_MODELO = 20
Public Const STRING_PADRAOCONTABITEM_CONTA = 255
Public Const STRING_PADRAOCONTABITEM_CCL = 255
Public Const STRING_PADRAOCONTABITEM_CREDITO = 255
Public Const STRING_PADRAOCONTABITEM_DEBITO = 255
Public Const STRING_PADRAOCONTABITEM_HISTORICO = 255
Public Const STRING_PADRAOCONTABITEM_PRODUTO = 255
Public Const STRING_MNEMONICOCTB_MNEMONICO = 20
Public Const STRING_MNEMONICOCTB_MNEMONICOCOMBO = 50
Public Const STRING_MNEMONICOCTB_MNEMONICODESC = 255
'Public Const STRING_NOME_CONTROLE = 50
Public Const STRING_FORMULAFUNCAO_FUNCAOCOMBO = 50
Public Const STRING_FORMULAFUNCAO_FUNCAODESC = 255
Public Const STRING_FORMULAOPERADOR_OPERADORCOMBO = 50
Public Const STRING_FORMULAOPERADOR_OPERADORDESC = 255
Public Const STRING_TRANSACAOCTB_TRANSACAO = 50
Public Const STRING_TRANSACAOCTB_TRANSACAOTELA = 50
Public Const STRING_MNEMONICOCTBVALOR_DESCRICAO = 50
Public Const STRING_MNEMONICOCTBVALOR_VALOR = 50

Public Const STRING_RELDRE_MODELO = 50
Public Const STRING_DRE_MODELO = 50
Public Const STRING_DRE_TITULO = 100

Public Const STRING_CATEGORIACLIENTE_CATEGORIA = 20
Public Const STRING_CATEGORIACLIENTE_DESCRICAO = 50
Public Const STRING_CATEGORIACLIENTEITEM_ITEM = 20
Public Const STRING_CATEGORIACLIENTEITEM_DESCRICAO = 50

'Incluído por Luiz Nogueira em 03/03/04
Public Const STRING_CATEGORIAFORNECEDOR_CATEGORIA = 20
Public Const STRING_CATEGORIAFORNECEDOR_DESCRICAO = 50
Public Const STRING_CATEGORIAFORNECEDORITEM_ITEM = 20
Public Const STRING_CATEGORIAFORNECEDORITEM_DESCRICAO = 50

'Passou a ser implementada em AdmLib.ClassConstCust
'Public Const STRING_FORNECEDOR_NOME_REDUZIDO = 20
Public Const STRING_FILIAL_FORNECEDOR_NOME = 50
Public Const STRING_FILIAL_FORNECEDOR_OBS = 100

Public Const STRING_ALMOXARIFADO_NOME_REDUZIDO = 20
Public Const STRING_ALMOXARIFADO_DESCRICAO = 50

Public Const STRING_UM_SIGLA = 5
Public Const STRING_UM_NOME = 20

Public Const STRING_COMCONFIG_CODIGO = 50
Public Const STRING_COMCONFIG_DESCRICAO = 150

Public Const STRING_NOME_TSK = 8

Public Const STRING_NATMOVCTA_CODIGO = 20
Public Const STRING_NATMOVCTA_DESCRICAO = 255

Public Const NATUREZA_TIPO_INDEFINIDA = 0
Public Const NATUREZA_TIPO_PAGAMENTO = 1
Public Const NATUREZA_TIPO_RECEBIMENTO = 2

'Constante utilizadas nas regras de comissões
Public Const VENDEDOR_DIRETO = 0
Public Const VENDEDOR_INDIRETO = 1
Public Const VENDEDOR_TODOS = 2

'Estruturas
Type typeConta
    sConta As String
    sDescricao As String
    iTipo As Integer '1-Sintetico  2-Sintetico Final  3-Analitico
End Type

Type typeCcl
    sCcl As String
    sDescCcl As String
    iTipoCcl As Integer
    iAtivo As Integer
End Type
    
Type typePlanoConta
    iNivelConta As Integer
    sConta As String
    sDescConta As String
    iTipoConta As Integer
    lContaSimples As Long
    iNatureza As Integer
    iDigitoVerif As Integer
    iDigitoVerifSimples As Integer
    iHistPadrao As Integer
    iAtivo As Integer
    iUsaContaSimples As Integer
    dSldIni As Double
    iCategoria As Integer
    iCP As Integer
    iCR As Integer
    iTES As Integer
    iFAT As Integer
    iEST As Integer
    iCOM As Integer
    iFIS As Integer
    iLJ As Integer
    iFluxoCaixa As Integer
    iNaturezaSped As Integer
End Type
    
Type typeLote
    iFilialEmpresa As Integer
    iLote As Integer
    iExercicio As Integer
    sOrigem As String
    iPeriodo As Integer
    iStatus As Integer
    dTotCre As Double
    dTotDeb As Double
    dTotInf As Double
    sIdOriginal As String
    iNumLancInf As Integer
    iNumLancAtual As Integer
    iIdAtualizacao As Integer
    iNumDocInf As Integer
    iNumDocAtual As Integer
End Type

Type typeConfiguracao
    sGrupoReceita As String
    sGrupoDespesa As String
    sGrupoAtivo As String
    sGrupoPassivo As String
    iIdAtualizacao As Integer
    iUsoCcl As Integer
    iDocPorPeriodo As Integer
    iLotePorPeriodo As Integer
    iTipoContaDefault As Integer
    iNaturezaDefault As Integer
    iHistPadrao As Integer
    dtDataImplantacao As Date
    lDocAuto As Long
    iContabCentralizada As Integer
    iContabGerencial As Integer
    iFilialAuxiliar As Integer
End Type

Type typeOrigem
    sOrigem As String
    sDescricao As String
    iContabilidade As Integer
End Type

Type typeSldMesEst
    iAno As Integer
    iFilialEmpresa As Integer
    sProduto As String
    dCustoMedioProducaoInicial As Double
    dQuantInicial As Double
    dValorInicial As Double
    dQuantInicialCusto As Double
    dValorInicialCusto As Double
    adQuantEnt(1 To 12) As Double
    adValorEnt(1 To 12) As Double
    adQuantSai(1 To 12) As Double
    adQuantCons(1 To 12) As Double
    adQuantVend(1 To 12) As Double
    adQuantVendConsig3(1 To 12) As Double
    adValorSai(1 To 12) As Double
    adCustoMedio(1 To 12) As Double
    adCustoProducao(1 To 12) As Double
    adCustoStandard(1 To 12) As Double
    aiStatus(1 To 12) As Integer
    adQuantComp(1 To 12) As Double
    adValorComp(1 To 12) As Double
    adValorVend(1 To 12) As Double
    adValorVendConsig3(1 To 12) As Double
    adValorCons(1 To 12) As Double
    adSaldoQuantCusto(1 To 12) As Double
    adSaldoValorCusto(1 To 12) As Double
    adSaldoQuantRecIndl(1 To 12) As Double
    adSaldoValorRecIndl(1 To 12) As Double
    dQuantInicialRecIndl As Double
    dValorInicialRecIndl As Double
End Type

Type typeSldMesEst1
    iAno As Integer
    iFilialEmpresa As Integer
    sProduto As String
    dQuantInicialConsig3 As Double
    dValorInicialConsig3 As Double
    dQuantInicialDemo3 As Double
    dValorInicialDemo3 As Double
    dQuantInicialConserto3 As Double
    dValorInicialConserto3 As Double
    dQuantInicialOutros3 As Double
    dValorInicialOutros3 As Double
    dQuantInicialBenef3 As Double
    dValorInicialBenef3 As Double
    adSaldoQuantConsig3(1 To 12) As Double
    adSaldoValorConsig3(1 To 12) As Double
    adSaldoQuantDemo3(1 To 12) As Double
    adSaldoValorDemo3(1 To 12) As Double
    adSaldoQuantConserto3(1 To 12) As Double
    adSaldoValorConserto3(1 To 12) As Double
    adSaldoQuantOutros3(1 To 12) As Double
    adSaldoValorOutros3(1 To 12) As Double
    adSaldoQuantBenef3(1 To 12) As Double
    adSaldoValorBenef3(1 To 12) As Double
    adCustoMedioConsig3(1 To 12) As Double
    adCustoMedioDemo3(1 To 12) As Double
    adCustoMedioConserto3(1 To 12) As Double
    adCustoMedioOutros3(1 To 12) As Double
    adCustoMedioBenef3(1 To 12) As Double
End Type

Type typeSldMesEst2
    iAno As Integer
    iFilialEmpresa As Integer
    sProduto As String
    dQuantInicialConsig As Double
    dValorInicialConsig As Double
    dQuantInicialDemo As Double
    dValorInicialDemo As Double
    dQuantInicialConserto As Double
    dValorInicialConserto As Double
    dQuantInicialOutros As Double
    dValorInicialOutros As Double
    dQuantInicialBenef As Double
    dValorInicialBenef As Double
    adSaldoQuantConsig(1 To 12) As Double
    adSaldoValorConsig(1 To 12) As Double
    adSaldoQuantDemo(1 To 12) As Double
    adSaldoValorDemo(1 To 12) As Double
    adSaldoQuantConserto(1 To 12) As Double
    adSaldoValorConserto(1 To 12) As Double
    adSaldoQuantOutros(1 To 12) As Double
    adSaldoValorOutros(1 To 12) As Double
    adSaldoQuantBenef(1 To 12) As Double
    adSaldoValorBenef(1 To 12) As Double
    adCustoMedioConsig(1 To 12) As Double
    adCustoMedioDemo(1 To 12) As Double
    adCustoMedioConserto(1 To 12) As Double
    adCustoMedioOutros(1 To 12) As Double
    adCustoMedioBenef(1 To 12) As Double
End Type

Type typeSldDiaEstAlm
    iAlmoxarifado As Integer
    sProduto As String
    dtData As Date
    dQuantEntrada As Double
    dQuantSaida As Double
    dQuantComp As Double
    dQuantCons As Double
    dQuantVend As Double
    dQuantVendConsig3 As Double
    dValorEntrada As Double
    dValorSaida As Double
    dValorCons As Double
    dValorComp As Double
    dValorVend As Double
    dValorVendConsig3 As Double
    dQuantEntCusto As Double
    dValorEntCusto As Double
    dQuantSaiCusto As Double
    dValorSaiCusto As Double
    dQuantEntConsig3 As Double
    dValorEntConsig3 As Double
    dQuantSaiConsig3 As Double
    dValorSaiConsig3 As Double
    dQuantEntDemo3 As Double
    dValorEntDemo3 As Double
    dQuantSaiDemo3 As Double
    dValorSaiDemo3 As Double
    dQuantEntConserto3 As Double
    dValorEntConserto3 As Double
    dQuantSaiConserto3 As Double
    dValorSaiConserto3 As Double
    dQuantEntOutros3 As Double
    dValorEntOutros3 As Double
    dQuantSaiOutros3 As Double
    dValorSaiOutros3 As Double
    dQuantEntBenef3 As Double
    dValorEntBenef3 As Double
    dQuantSaiBenef3 As Double
    dValorSaiBenef3 As Double
    dQuantEntConsig As Double
    dValorEntConsig As Double
    dQuantSaiConsig As Double
    dValorSaiConsig As Double
    dQuantEntDemo As Double
    dValorEntDemo As Double
    dQuantSaiDemo As Double
    dValorSaiDemo As Double
    dQuantEntConserto As Double
    dValorEntConserto As Double
    dQuantSaiConserto As Double
    dValorSaiConserto As Double
    dQuantEntOutros As Double
    dValorEntOutros As Double
    dQuantSaiOutros As Double
    dValorSaiOutros As Double
    dQuantEntBenef As Double
    dValorEntBenef As Double
    dQuantSaiBenef As Double
    dValorSaiBenef As Double
    dQuantEntRecIndl As Double
    dValorEntRecIndl As Double
    dQuantSaiRecIndl As Double
    dValorSaiRecIndl As Double
End Type

Type typeSldDiaEst
    iAlmoxarifado As Integer
    sProduto As String
    dtData As Date
    dQuantEntrada As Double
    dQuantSaida As Double
    dQuantCons As Double
    dQuantVend As Double
    dQuantVendConsig3 As Double
    dValorEntrada As Double
    dValorSaida As Double
    dQuantComp As Double
    dValorComp As Double
    dValorVend As Double
    dValorVendConsig3 As Double
    dValorCons As Double
    dQuantEntCusto As Double
    dValorEntCusto As Double
    dQuantSaiCusto As Double
    dValorSaiCusto As Double
    dQuantEntConsig3 As Double
    dValorEntConsig3 As Double
    dQuantSaiConsig3 As Double
    dValorSaiConsig3 As Double
    dQuantEntDemo3 As Double
    dValorEntDemo3 As Double
    dQuantSaiDemo3 As Double
    dValorSaiDemo3 As Double
    dQuantEntConserto3 As Double
    dValorEntConserto3 As Double
    dQuantSaiConserto3 As Double
    dValorSaiConserto3 As Double
    dQuantEntOutros3 As Double
    dValorEntOutros3 As Double
    dQuantSaiOutros3 As Double
    dValorSaiOutros3 As Double
    dQuantEntBenef3 As Double
    dValorEntBenef3 As Double
    dQuantSaiBenef3 As Double
    dValorSaiBenef3 As Double
    dQuantEntConsig As Double
    dValorEntConsig As Double
    dQuantSaiConsig As Double
    dValorSaiConsig As Double
    dQuantEntDemo As Double
    dValorEntDemo As Double
    dQuantSaiDemo As Double
    dValorSaiDemo As Double
    dQuantEntConserto As Double
    dValorEntConserto As Double
    dQuantSaiConserto As Double
    dValorSaiConserto As Double
    dQuantEntOutros As Double
    dValorEntOutros As Double
    dQuantSaiOutros As Double
    dValorSaiOutros As Double
    dQuantEntBenef As Double
    dValorEntBenef As Double
    dQuantSaiBenef As Double
    dValorSaiBenef As Double
    dQuantEntRecIndl As Double
    dValorEntRecIndl As Double
    dQuantSaiRecIndl As Double
    dValorSaiRecIndl As Double
End Type

Type typeSldMesEstAlm
    iAlmoxarifado As Integer
    iAno As Integer
    sProduto As String
    dQuantInicial As Double
    dValorInicial As Double
    dQuantInicialCusto As Double
    dValorInicialCusto As Double
    adQuantEnt(1 To 12) As Double
    adValorEnt(1 To 12) As Double
    adQuantSai(1 To 12) As Double
    adQuantCons(1 To 12) As Double
    adQuantVend(1 To 12) As Double
    adQuantVendConsig3(1 To 12) As Double
    adValorSai(1 To 12) As Double
    aiStatus(1 To 12) As Integer
    adQuantComp(1 To 12) As Double
    adValorComp(1 To 12) As Double
    adValorVend(1 To 12) As Double
    adValorVendConsig3(1 To 12) As Double
    adValorCons(1 To 12) As Double
    adSaldoQuantCusto(1 To 12) As Double
    adSaldoValorCusto(1 To 12) As Double
    adSaldoQuantRecIndl(1 To 12) As Double
    adSaldoValorRecIndl(1 To 12) As Double
    dQuantInicialRecIndl As Double
    dValorInicialRecIndl As Double
End Type


Type typeSldMesEstAlm1
    iAlmoxarifado As Integer
    iAno As Integer
    sProduto As String
    dQuantInicialConsig3 As Double
    dValorInicialConsig3 As Double
    dQuantInicialDemo3 As Double
    dValorInicialDemo3 As Double
    dQuantInicialConserto3 As Double
    dValorInicialConserto3 As Double
    dQuantInicialOutros3 As Double
    dValorInicialOutros3 As Double
    dQuantInicialBenef3 As Double
    dValorInicialBenef3 As Double
    adSaldoQuantConsig3(1 To 12) As Double
    adSaldoValorConsig3(1 To 12) As Double
    adSaldoQuantDemo3(1 To 12) As Double
    adSaldoValorDemo3(1 To 12) As Double
    adSaldoQuantConserto3(1 To 12) As Double
    adSaldoValorConserto3(1 To 12) As Double
    adSaldoQuantOutros3(1 To 12) As Double
    adSaldoValorOutros3(1 To 12) As Double
    adSaldoQuantBenef3(1 To 12) As Double
    adSaldoValorBenef3(1 To 12) As Double
End Type

Type typeSldMesEstAlm2
    iAlmoxarifado As Integer
    iAno As Integer
    sProduto As String
    dQuantInicialConsig As Double
    dValorInicialConsig As Double
    dQuantInicialDemo As Double
    dValorInicialDemo As Double
    dQuantInicialConserto As Double
    dValorInicialConserto As Double
    dQuantInicialOutros As Double
    dValorInicialOutros As Double
    dQuantInicialBenef As Double
    dValorInicialBenef As Double
    adSaldoQuantConsig(1 To 12) As Double
    adSaldoValorConsig(1 To 12) As Double
    adSaldoQuantDemo(1 To 12) As Double
    adSaldoValorDemo(1 To 12) As Double
    adSaldoQuantConserto(1 To 12) As Double
    adSaldoValorConserto(1 To 12) As Double
    adSaldoQuantOutros(1 To 12) As Double
    adSaldoValorOutros(1 To 12) As Double
    adSaldoQuantBenef(1 To 12) As Double
    adSaldoValorBenef(1 To 12) As Double
End Type


Type typeEstoqueMes
    iFilialEmpresa As Integer
    iAno As Integer
    iMes As Integer
    iFechamento As Integer
    iAlterado As Integer
    iCustoProdApurado As Integer
    lHorasMaquina As Long
    dCustoMatPrim As Double
    dGastosDiretos As Double
    dGastosIndiretos As Double
    dQuantFator1 As Double
    dCustoFator1 As Double
    dQuantFator2 As Double
    dCustoFator2 As Double
    dQuantFator3 As Double
    dCustoFator3 As Double
    dQuantFator4 As Double
    dCustoFator4 As Double
    dQuantFator5 As Double
    dCustoFator5 As Double
    dQuantFator6 As Double
    dCustoFator6 As Double
End Type

Type typeLancamento
    iFilialEmpresa As Integer
    sOrigem As String
    iExercicio As Integer
    iPeriodoLan As Integer
    lDoc As Long
    iSeq As Integer
    iLote As Integer
    iPeriodoLote As Integer
    dtData As Date
    sConta As String
    sCcl As String
    sHistorico As String
    dValor As Double
    lNumIntDoc As Long
    iFilialCliForn As Integer
    lCliForn As Long
    iTransacao As Integer
    iAglutina As Integer
    lDocAglutinado As Long
    iSeqAglutinado As Integer
    sProduto As String
    iApropriaCRProd As Integer
    lLoteOrigem As Long 'utilizado por lançamento pre-pendente
    lContaSimples As Long
    iSeqContraPartida As Integer
    iEscaninho_Custo As Integer
    dValorLivroAuxiliar As Double
    iClienteFornecedor As Integer 'indica se um cliente ou fornecedor está associado ao lançamento
    sDocOrigem As String 'indica o documento que originou o lancamento
    dQuantidade As Double 'se produto estiver preenchido indica a quantidade do produto. É importante manter para fins de reprocessamento.
    dtDataEstoque As Date 'indica a data com que foi registrado o lançamento em termos de estoque. É importante para fins de reprocessamento.
    iApropriacao As Integer 'se produto estiver preenchido indica a apropriação do produto
    iStatus As Integer
    iCredDeb As Integer '1=Credito 2=Debito 0=Sem indicação
    iCredDebLivroAuxiliar As Integer '1=Credito 2=Debito 0=Sem indicação
    sModelo As String
    iGerencial As Integer
    iSubTipo As Integer
    sUsuario As String
End Type

Type typeLancamento_Sort
    dValor As Double
    iExercicio As Integer
    iPeriodoLan As Integer
    lDoc As Long
    iSeq As Integer
    iLote As Integer
    iPeriodoLote As Integer
    iDummy As Integer
    dtData As Date
    sConta As String * STRING_CONTA_MAIS_UM
    sCcl As String * STRING_CCL_MAIS_UM
    sHistorico As String * STRING_HISTORICO_MAIS_UM
    sOrigem As String * STRING_ORIGEM_MAIS_UM
    iFilialEmpresa As Integer
    lNumIntDoc As Long
    iFilialCliForn As Integer
    lCliForn As Long
    iTransacao As Integer
    iAglutina As Integer
    iEscaninho_Custo As Integer
    dValorLivroAuxiliar As Double
    iClienteFornecedor As Integer 'indica se um cliente ou fornecedor está associado ao lançamento
    iCredDeb As Integer '1=Credito 2=Debito 0=Sem indicação
    sDocOrigem As String * STRING_DOCORIGEM_MAIS_UM 'indica o documento que originou o lancamento
    iGerencial As Integer
End Type



Type typePeriodo
    iExercicio As Integer
    iPeriodo As Integer
    sNomeExterno As String
    iLancamentos As Integer
    iApurado As Integer
    dtDataInicio As Date
    dtDataFim As Date
    iLote As Integer
    iFechado As Integer
    iFechadoCTB As Integer
End Type

Type typeExercicio
    iExercicio As Integer
    iNumPeriodos As Integer
    iStatus As Integer
    iLoteApuracao As Integer
    sNomeExterno As String
    dtDataInicio As Date
    dtDataFim As Date
End Type

Type typeDocAuto
    lDoc As Long
    iSeq As Integer
    sDescricao As String
    sConta As String
    sCcl As String
    sHistorico As String
    dValor As Double
    sOrigem As String
    iSeqContraPartida As Integer
End Type

Type typeUnidadeMedida
    sSigla As String
    sNome As String
    iClasse As Integer
    sSiglaUMBase As String
    dQuantidade As Double
    iEditavel As Integer
    dtDataLog As Date
    iAtivo As Integer
End Type

Type typeRateioOn
    iCodigo As Integer
    iSeq As Integer
    sDescricao As String
    sConta As String
    sCcl As String
    sHistorico As String
    dPercentual As Double
End Type

Type typeOrcamento
    iExercicio As Integer
    sConta As String
    iPeriodo As Integer
    sCcl As String
    dValor As Double
End Type

Type typeSelecao
    sCta_I As String
    sCta_F As String
    sDtIni_I As String
    sDtIni_F As String
    sDtFim_I As String
    sDtFim_F As String
End Type


Type typeRateioOff
    sCclOrigem As String
    sDescricao As String
    sContaCre As String
    iTipo As Integer
    sConta As String
    sCcl As String
    dPercentual As Double
    lSeq As Long
End Type

Type typeCTBConfig
    sCodigo As String
    iFilialEmpresa As Integer
    sDescricao As String
    iTipo As Integer
    sConteudo As String
End Type

Type typeApuracao
    iFilialEmpresa As Integer
    iExercicio As Integer
    iPeriodo As Integer
    iLote As Integer
    dtData As Date
    sConta As String
    lDoc As Long
    sConta_Resultado As String
    sConta_Ponte As String
    sCcl_ContaPonte As String
    sConta_Inicial As String
    sConta_Final As String
    lComando1 As Long
    lComando2 As Long
    lComando3 As Long
    lComando4 As Long
    dTotCre As Double
    dTotDeb As Double
    dSaldo As Double
    iNumLanc As Integer
    sPeriodo As String
    sHistorico As String
    sOrigem_Apuracao As String
    sOrigem_Estorno As String
    lComando1_Ccl As Long
    lComando2_Ccl As Long
    lComando1_Conta As Long
    lComando2_Conta As Long
    iNumPeriodos As Integer
    iPeriodo_Inicial As Integer
    iPeriodo_Final As Integer
    iUsoCcl As Integer
    lCodigoApuracao As Long
    colContasApuracao As Collection
    sSQL As String
    asConta(20) As Variant
    iStatusExercicioFilial As Integer
    iExisteLoteApuracao As Integer
    iZeraRD As Integer
    iSeq As Integer
End Type

Type typeFilialFornecedor
    lCodFornecedor As Long
    iCodFilial As Integer
    sNome As String
    lEndereco As Long
    sCgc As String
    sInscricaoEstadual As String
    sInscricaoMunicipal As String
    sContaContabil As String
    sContaFornConsig As String
    iBanco As Integer
    sAgencia As String
    sContaCorrente As String
    sObservacao As String
    sInscricaoINSS As String
    iTipoCobranca As Integer
    sContaDespesa As String
    iGeraCredICMS As Integer
    iTipoFrete As Integer
    sInscricaoSuframa As String
    iRegimeTributario As Integer
    iIEIsento As Integer
    iIENaoContrib As Integer

    'nfe 3.10
    sIdEstrangeiro As String

End Type

Public Const CONDPAGTO_TIPODATABASE_EMISSAO = 1
Public Const CONDPAGTO_TIPODATABASE_ENTREGA = 2
Public Const CONDPAGTO_TIPODATABASE_PARCANTERIOR = 3
Public Const CONDPAGTO_TIPODATABASE_DATAFIXA = 4
Public Const CONDPAGTO_TIPODATABASE_DATAPEDIDO = 5

Public Const CONDPAGTO_MODIFICADOR_VAZIO = 0
Public Const CONDPAGTO_MODIFICADOR_FORAMES = 1
Public Const CONDPAGTO_MODIFICADOR_FORAQUINZENA = 2
Public Const CONDPAGTO_MODIFICADOR_FORASEMANA = 3

Public Const CONDPAGTO_TIPOINTERVALO_DIAS = 1
Public Const CONDPAGTO_TIPOINTERVALO_DIAS_UTEIS = 2
Public Const CONDPAGTO_TIPOINTERVALO_DIAMES = 3
Public Const CONDPAGTO_TIPOINTERVALO_DIASEMANA = 4

Type typeCondicaoPagto
    iCodigo As Integer
    sDescReduzida As String
    sDescricao As String
    iEmPagamento As Integer
    iEmRecebimento As Integer
    iNumeroParcelas As Integer
    iDiasParaPrimeiraParcela As Integer
    iIntervaloParcelas As Integer
    iMensal As Integer
    iDiaDoMes As Integer
    dAcrescimoFinanceiro As Double
    iModificador As Integer
    iDataFixa As Integer
    iPreCadastrado As Integer
    iCargoMinimo As Integer
    iFormaPagamento As Integer
    dTetoParcela As Double
End Type

Type typeCondicaoPagtoParc
    iCodigo As Integer
    iSeq As Integer
    iTipoDataBase As Integer
    iTipoIntervalo As Integer
    iDias As Integer
    iModificador As Integer
    dPercReceb As Double
End Type

Type typePeriodosFilial
    iFilialEmpresa As Integer
    iExercicio As Integer
    iPeriodo As Integer
    iLancamentos As Integer
    iApurado As Integer
    iLote As Integer
    iFechado As Integer
    iFechadoCTB As Integer
    dtDataApuracao As Date
    lDocApuracao As Long
End Type

Type typeExerciciosFilial
    iFilialEmpresa As Integer
    iExercicio As Integer
    iStatus As Integer
    iLoteApuracao As Integer
    dtDataApuracao As Date
    lDocApuracao As Long
End Type

Type typeMnemonicoCTB
    sModulo As String
    iTransacao As Integer
    sMnemonico As String
    iTipo As Integer
    iNumParam As Integer
    iParam1 As Integer
    iParam2 As Integer
    iParam3 As Integer
    sNomeGrid As String
    sMnemonicoCombo As String
    sMnemonicoDesc As String
End Type

Type typeMnemonicoFPreco
    lNumIntDoc As Long
    iFilialEmpresa As Integer
    iEscopo As Integer
    sItemCategoria As String
    sProduto As String
    iTabelaPreco As Integer
    sMnemonico As String
    iTipo As Integer
    iNumParam As Integer
    iParam1 As Integer
    iParam2 As Integer
    iParam3 As Integer
    sMnemonicoDesc As String
    sExpressao As String
    iFuncao As Integer
End Type

Type typeFormulaFuncao
    sFuncaoCombo As String
    sFuncaoDesc As String
End Type

Type typeFormulaOperador
    sOperadorCombo As String
    sOperadorDesc As String
End Type

Type typeTransacaoCTB
    sSigla As String
    sTransacao As String
    iCodigo As Integer
End Type

Type typePadraoContab
    sModulo As String
    iTransacao As Integer
    sModelo As String
    iPadrao As Integer
End Type

Type typePadraoContabItem
    sModulo As String
    iTransacao As Integer
    sModelo As String
    iItem As Integer
    sConta As String
    sCcl As String
    sCredito As String
    sDebito As String
    sHistorico As String
    iCusto As Integer
    sProduto As String
    iAglutina As Integer
    iGerencial As Integer
End Type

Type typeMnemonicoCTBValor
    sMnemonico As String
    sDescricao As String
    sValor As String
End Type

Type typeRelDRE
    iCodigo As Integer
    iTipo As Integer
    iNivel As Integer
    sTitulo As String
    dValor As Double
    sModelo As String
    iPosicao As Integer
    iImprime As Integer
    iExercicio As Integer
End Type

Type typeRelDREFormula
    iCodigo As Integer
    iItem As Integer
    iOperacao As Integer
    sModelo As String
    iCodigoFormula As Integer
    sFormula As String
End Type

Type typeRelDREConta
    iCodigo As Integer
    iItem As Integer
    sContaInicial As String
    sContaFinal As String
    sModelo As String
    sCclInicial As String
    sCclFinal As String
End Type

Type typeContas
    sConta_Resultado As String
    sConta_Ponte As String
    sConta_Receita_Inicial As String
    sConta_Receita_Final As String
    sConta_Despesa_Inicial As String
    sConta_Despesa_Final As String
End Type

Type typeContas_Fechamento
    sConta_Ativo_Inicial As String
    sConta_Ativo_Final As String
    sConta_Passivo_Inicial As String
    sConta_Passivo_Final As String
End Type

Type typeRelDMPL
    iLinha As Integer
    iColuna As Integer
    iTipo As Integer
    sTitulo As String
    dValor As Double
    dValorExercAnt As Double
    sModelo As String
    iExercicio As Integer
End Type

Type typeRelDMPLFormula
    iLinha As Integer
    iColuna As Integer
    iItem As Integer
    iOperacao As Integer
    sModelo As String
    iLinhaFormula As Integer
    iColunaFormula As Integer
End Type

Type typeRelDMPLConta
    iLinha As Integer
    iColuna As Integer
    iItem As Integer
    sContaInicial As String
    sContaFinal As String
    sModelo As String
End Type

Type typeProcessa_Lancamento1
    lComando As Long
    iFilialEmpresa As Integer
    iExercicio As Integer
    iPeriodo As Integer
    sConta As String
    dSaldoAnterior As Double
    dDebito As Double
    dCredito As Double
    iFim_de_Arquivo As Integer
    dAcumDebito As Double
    dAcumCredito As Double
    dAcumSaldoAnterior As Double
End Type

'Type usado para gravacao de historico do ccl
Type typeCclHistorico
    lNumIntDoc As Long
    dtDataAtualizacao As Date
    sCodigoCcl As String
    iTipoCcl As Integer
    sDescCcl As String
End Type

'Type Usado para gravacao de historico do Plano de Conta
Type typePlanoContaHistorico
    lNumIntDoc As Long
    dtDataAtualizacao As Date
    sCodigo As String
    iTipo As Integer
    sContaPai As String
    sDescricao As String
End Type

'Type usado para manipulação dos registros de ComissoesRegras
Type typeComissoesRegras
    lNumIntDoc As Long
    iVendedor As Integer
    sRegra As String
    lOrdenacao As Long
    sValorBase As String
    sPercComissao As String
    dPercComissaoEmiss As Double
    iVendedorIndireto As Integer
    lNumIntDocOrigem As Long
End Type

Type typeNatMovCta
    sCodigo As String
    sDescricao As String
    iTipo As Integer
    iFluxoCaixa As Integer
    lGrupo As Long
End Type

'*************************************************************************************************************************************************************************************************************************************
' Funções e Declarações usados na maquina de expressões
'*************************************************************************************************************************************************************************************************************************************

'Public Const TIPO_NUMERICO = 0
'Public Const TIPO_DATA = 1
'Public Const TIPO_HORA = 2
'Public Const TIPO_TEXTO = 3
'Public Const TIPO_BOOLEANO = 4
'Public Const TIPO_INVALIDO = 9

Public Const NUMERICO As String = "Numérico"
Public Const Data As String = "Data"
Public Const HORA As String = "Hora"
Public Const TEXTO As String = "Texto"
Public Const BOOLEANO As String = "Booleano"
Public Const INVALIDO As String = "Inválido"

'indica qual a formula que está sendo executada
Public Const CAMPO_CONTA = 1
Public Const CAMPO_CCL = 2
Public Const CAMPO_CREDITO = 3
Public Const CAMPO_DEBITO = 4
Public Const CAMPO_HISTORICO = 5
Public Const CAMPO_PRODUTO = 6
Public Const CAMPO_AGLUTINA = 7
Public Const CAMPO_ESCANINHO_CUSTO = 8
Public Const CAMPO_GERENCIAL = 9

Public Const STRING_PLANOCONTAREFMODELO_DESCRICAO = 50
Public Const STRING_PLANOCONTAREF_DESCRICAO = 250
Public Const STRING_PLANOCONTAREF_ORIENTACAO = 250


'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typePlanoContaRef
    lCodigoModelo As Long
    sConta As String
    sDescricao As String
    sOrientacao As String
    iTipo As Integer
    sContaImp As String
    iTipoImp As Integer
    dtValidadeDe As Date
    dtValidadeAte As Date
    sConta0 As String
    sContaPai As String
    iNatureza As Integer
End Type

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typePlanoContaRefModelo
    lCodigo As Long
    sDescricao As String
    iOficial As Integer
    iAnoVigencia As Integer
    sUsuarioCad As String
    dtDataCad As Date
    dHoraCad As Double
    sUsuarioAlt As String
    dtDataAlt As Date
    dHoraAlt As Double
    iTipo As Integer
End Type

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typePlanoContaRefConfig
    lCodigoModelo As Long
    sConta As String
    iSeq As Integer
    sContaInicial As String
    sContaFinal As String
    sCclInicial As String
    sCclFinal As String
    iSubtrai As Integer
End Type

Public Const STRING_FORMA_PAGTO_DESCRICAO = 50

Public Const REGRAMSG_TIPODOC_NF = 0
Public Const REGRAMSG_TIPODOC_ITEMNF = 1

Public Const REGRAMSG_TIPODOC_NF_TEXTO = "Nota Fiscal"
Public Const REGRAMSG_TIPODOC_ITEMNF_TEXTO = "Item da Nota Fiscal"

Public Const REGRAMSG_TIPOMSG_NORMAL = 0
Public Const REGRAMSG_TIPOMSG_CORPO = 1

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typeRegrasMsg
    iTipoDoc As Integer
    iSeq As Integer
    iTipoMsg As Integer
    sRegra1 As String
    sRegra2 As String
    sRegra3 As String
    sRegra4 As String
    sRegra5 As String
    sMensagem As String
End Type

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typeMensagensRegra
    iTipoDoc As Integer
    lNumIntDoc As Long
    iSeq As Integer
    sMensagem As String
    iTipoMsg As Integer
End Type

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typeMnemonicoRegrasMsg
    iTipoDoc As Integer
    sMnemonico As String
    iTipo As Integer
    iNumParam As Integer
    iParam1 As Integer
    iParam2 As Integer
    iParam3 As Integer
    sNomeGrid As String
    sMnemonicoCombo As String
    sMnemonicoDesc As String
End Type

Type typeSldDiaEstTerc
    iFilialEmpresa As Integer
    sProduto As String
    dtData As Date
    lFornecedor As Long
    iFilialForn As Integer
    lCliente As Long
    iFilialCli As Integer
    dQuantEntConsig3 As Double
    dValorEntConsig3 As Double
    dQuantSaiConsig3 As Double
    dValorSaiConsig3 As Double
    dQuantEntDemo3 As Double
    dValorEntDemo3 As Double
    dQuantSaiDemo3 As Double
    dValorSaiDemo3 As Double
    dQuantEntConserto3 As Double
    dValorEntConserto3 As Double
    dQuantSaiConserto3 As Double
    dValorSaiConserto3 As Double
    dQuantEntOutros3 As Double
    dValorEntOutros3 As Double
    dQuantSaiOutros3 As Double
    dValorSaiOutros3 As Double
    dQuantEntBenef3 As Double
    dValorEntBenef3 As Double
    dQuantSaiBenef3 As Double
    dValorSaiBenef3 As Double
    dQuantEntConsig As Double
    dValorEntConsig As Double
    dQuantSaiConsig As Double
    dValorSaiConsig As Double
    dQuantEntDemo As Double
    dValorEntDemo As Double
    dQuantSaiDemo As Double
    dValorSaiDemo As Double
    dQuantEntConserto As Double
    dValorEntConserto As Double
    dQuantSaiConserto As Double
    dValorSaiConserto As Double
    dQuantEntOutros As Double
    dValorEntOutros As Double
    dQuantSaiOutros As Double
    dValorSaiOutros As Double
    dQuantEntBenef As Double
    dValorEntBenef As Double
    dQuantSaiBenef As Double
    dValorSaiBenef As Double
End Type

Type typeSldMesEst1Terc
    iFilialEmpresa As Integer
    iAno As Integer
    sProduto As String
    lFornecedor As Long
    iFilialForn As Integer
    lCliente As Long
    iFilialCli As Integer
    dQuantInicialConsig3 As Double
    dValorInicialConsig3 As Double
    dQuantInicialDemo3 As Double
    dValorInicialDemo3 As Double
    dQuantInicialConserto3 As Double
    dValorInicialConserto3 As Double
    dQuantInicialOutros3 As Double
    dValorInicialOutros3 As Double
    dQuantInicialBenef3 As Double
    dValorInicialBenef3 As Double
    adSaldoQuantConsig3(1 To 12) As Double
    adSaldoValorConsig3(1 To 12) As Double
    adSaldoQuantDemo3(1 To 12) As Double
    adSaldoValorDemo3(1 To 12) As Double
    adSaldoQuantConserto3(1 To 12) As Double
    adSaldoValorConserto3(1 To 12) As Double
    adSaldoQuantOutros3(1 To 12) As Double
    adSaldoValorOutros3(1 To 12) As Double
    adSaldoQuantBenef3(1 To 12) As Double
    adSaldoValorBenef3(1 To 12) As Double
    adCustoMedioConsig3(1 To 12) As Double
    adCustoMedioDemo3(1 To 12) As Double
    adCustoMedioConserto3(1 To 12) As Double
    adCustoMedioOutros3(1 To 12) As Double
    adCustoMedioBenef3(1 To 12) As Double
End Type

Type typeSldMesEst2Terc
    iFilialEmpresa As Integer
    iAno As Integer
    sProduto As String
    lFornecedor As Long
    iFilialForn As Integer
    lCliente As Long
    iFilialCli As Integer
    dQuantInicialConsig As Double
    dValorInicialConsig As Double
    dQuantInicialDemo As Double
    dValorInicialDemo As Double
    dQuantInicialConserto As Double
    dValorInicialConserto As Double
    dQuantInicialOutros As Double
    dValorInicialOutros As Double
    dQuantInicialBenef As Double
    dValorInicialBenef As Double
    adSaldoQuantConsig(1 To 12) As Double
    adSaldoValorConsig(1 To 12) As Double
    adSaldoQuantDemo(1 To 12) As Double
    adSaldoValorDemo(1 To 12) As Double
    adSaldoQuantConserto(1 To 12) As Double
    adSaldoValorConserto(1 To 12) As Double
    adSaldoQuantOutros(1 To 12) As Double
    adSaldoValorOutros(1 To 12) As Double
    adSaldoQuantBenef(1 To 12) As Double
    adSaldoValorBenef(1 To 12) As Double
    adCustoMedioConsig(1 To 12) As Double
    adCustoMedioDemo(1 To 12) As Double
    adCustoMedioConserto(1 To 12) As Double
    adCustoMedioOutros(1 To 12) As Double
    adCustoMedioBenef(1 To 12) As Double
End Type

'TYPE CRIADO AUTOMATICAMENTE PELA TELA BROWSECRIA
Type typeTiposPlanoContaRef
    iAnoBase As Integer
    iTipo As Integer
    sDescricao As String
End Type

