regsvr32 /s telasESTCro.ocx
regsvr32 /s RotinasMatCro.dll
regsvr32 /s RotinasPVCro.dll
regsvr32 /s GlobaisTelasESTCro.dll
regsvr32 /s GlobaisMATCro.dll
regsvr32 /s RotinasFATCro.dll
regsvr32 /s GlobaisTelasFATCro.dll
regsvr32 /s GlobaisAdmCro.dll
regsvr32 /s TelasFATCro.ocx
regsvr32 /s GlobaisPVCro.dll
