'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe"),  _
 System.Xml.Serialization.XmlRootAttribute("retConsReciNFe", [Namespace]:="http://www.portalfiscal.inf.br/nfe", IsNullable:=false)>  _
Partial Public Class TRetConsReciNFe
    
    Private tpAmbField As TAmb
    
    Private verAplicField As String
    
    Private nRecField As String
    
    Private cStatField As String
    
    Private xMotivoField As String
    
    Private cUFField As TCodUfIBGE
    
    Private protNFeField() As TProtNFe
    
    Private versaoField As String
    
    '''<remarks/>
    Public Property tpAmb() As TAmb
        Get
            Return Me.tpAmbField
        End Get
        Set
            Me.tpAmbField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property verAplic() As String
        Get
            Return Me.verAplicField
        End Get
        Set
            Me.verAplicField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property nRec() As String
        Get
            Return Me.nRecField
        End Get
        Set
            Me.nRecField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property cStat() As String
        Get
            Return Me.cStatField
        End Get
        Set
            Me.cStatField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property xMotivo() As String
        Get
            Return Me.xMotivoField
        End Get
        Set
            Me.xMotivoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property cUF() As TCodUfIBGE
        Get
            Return Me.cUFField
        End Get
        Set
            Me.cUFField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("protNFe")>  _
    Public Property protNFe() As TProtNFe()
        Get
            Return Me.protNFeField
        End Get
        Set
            Me.protNFeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property versao() As String
        Get
            Return Me.versaoField
        End Get
        Set
            Me.versaoField = value
        End Set
    End Property
End Class

'''<remarks/>

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")>  _
Partial Public Class TProtNFe
    
    Private infProtField As TProtNFeInfProt
    
    Private versaoField As String
    
    '''<remarks/>
    Public Property infProt() As TProtNFeInfProt
        Get
            Return Me.infProtField
        End Get
        Set
            Me.infProtField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property versao() As String
        Get
            Return Me.versaoField
        End Get
        Set
            Me.versaoField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.portalfiscal.inf.br/nfe")>  _
Partial Public Class TProtNFeInfProt
    
    Private tpAmbField As TAmb
    
    Private verAplicField As String
    
    Private chNFeField As String
    
    Private dhRecbtoField As Date
    
    Private nProtField As String

    Private digValField As String

    Private cStatField As String
    
    Private xMotivoField As String
    
    Private idField As String

    Private SignatureField As String
    
    '''<remarks/>
    Public Property tpAmb() As TAmb
        Get
            Return Me.tpAmbField
        End Get
        Set
            Me.tpAmbField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property verAplic() As String
        Get
            Return Me.verAplicField
        End Get
        Set
            Me.verAplicField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property chNFe() As String
        Get
            Return Me.chNFeField
        End Get
        Set
            Me.chNFeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property dhRecbto() As Date
        Get
            Return Me.dhRecbtoField
        End Get
        Set
            Me.dhRecbtoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property nProt() As String
        Get
            Return Me.nProtField
        End Get
        Set
            Me.nProtField = value
        End Set
    End Property

    Public Property digVal() As String
        Get
            Return Me.digValField
        End Get
        Set(ByVal value As String)
            Me.digValField = value
        End Set
    End Property

    '''<remarks/>
    Public Property cStat() As String
        Get
            Return Me.cStatField
        End Get
        Set
            Me.cStatField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property xMotivo() As String
        Get
            Return Me.xMotivoField
        End Get
        Set
            Me.xMotivoField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property Id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property

    Public Property Signature() As String
        Get
            Return Me.SignatureField
        End Get
        Set(ByVal value As String)
            Me.SignatureField = value
        End Set
    End Property

End Class
