"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make group2d1.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make group2d.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make group2efull.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make group2ffull.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcusta.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustb.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustc.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustd.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcuste.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustf.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustg.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcusth.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcusti.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustj.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustk.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupcustl.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupInpal.vbg
"C:\Program Files\Microsoft Visual Studio\VB98\VB6.EXE" /make groupbolla.vbg
